### ISSUE TITLE
Change chown for osxfuse to not be recursive

### ISSUE THREAD

**Issue by bexelbie** [Homebrew/homebrew-cask#103217]
https://github.com/Homebrew/homebrew-cask/blob/09c30448e0bc24b349779bae479b5e032282cdeb/Casks/osxfuse.rb#L14

By design, set_ownership does.a recursive chown.  However, AIUI the history of this code, the goal is to ensure that the two directories themselves remain writeable.

Can we shift this to a `chown` without `-R` so we don't disrupt other files, with specifically set permissions in those directories?

**Comment by vitorgalvao** [comment]
Those directories seem too broad for a `set_ownership`. Being that they’re in a `postflight`, what’s likely happening is that `osxfuse` is screwing up those permissions without regard for other software, hence resetting them back.

> Can we shift this to a `chown` without `-R` so we don't disrupt other files, with specifically set permissions in those directories?

Can? Yes, by using `system_command` to call `chown` instead of using `set_ownership` (changing the behaviour of `set_ownership` wouldn’t make sense, as it would break other casks). But should we? I’m not so sure. If you can find compelling arguments and submit them with a PR, we can proceed from there.
