### ISSUE TITLE
Cannot execute `unrar` because of Developer license issues

### ISSUE THREAD

**Issue by sedeki** [Homebrew/homebrew-cask#104398]
When I `brew install rar`, and execute `unrar` (or `rar`) it says that the developer cannot be verified. I guess this has to do with the new license "feature" in macOS.

Is there an updated version from RarSoft?

**Comment by cho-m** [comment]
Homebrew installs the latest RAR 6.0.1.

The issue is probably that RarSoft doesn't sign their releases with an Apple Developer ID
(maybe due to the $99/yr cost for the ID).

---

For some possible workarounds:
- You might want to see if there is an option to allow inside `Security & Privacy > General` after running `unrar/rar`.
- You could also try seeing if it is possible to `Right-Click > Open ...` the `unrar/rar` from the Finder at `open "$(brew --prefix)/bin"`
- Not too sure about this, but some people mentioned allowing `Security & Privacy > Privacy > Developer Tools` for your terminal.

**Comment by vitorgalvao** [comment]
> [If you ignore this guide, your issue may be closed without review](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/app_cant_be_opened.md
