### ISSUE TITLE
It's still a bad idea to rely on Github mirror for Calibre

### ISSUE THREAD

**Issue by jtbayly** [Homebrew/homebrew-cask#104814]
### Provide a detailed description of the proposed feature

For what it's worth, this issue is still a problem:
https://github.com/Homebrew/homebrew-cask/issues/10039

As of right now Calibre cask is broken because a new version was released. There's really not a reason I can come up with why brew should fail to install Calibre at all just because a new version has been released.

### What is the motivation for the feature?

Keep "brew install --cask calibre" from breaking every time a new version is released (until somebody can get around to updating the cask).

### Example use case

My continuous integration installs Calibre, just for example, and now I have a failed build, with no obvious way to fix it except "wait and hope that somebody else approves the update soon."

**Comment by cho-m** [comment]
There is no ideal solution here:
- If the Cask uses **calibre-ebook.com**, then someone will complain about it being slow and request GitHub URL
  - May 2015 - #9934 / #9942
  - May 2020 - #81790
- If the Cask uses **GitHub**, then someone will complain about new update breaking install
  - May 2015- #10039
  - Apr 2021 - This issue.

---

Most likely, if this is changed to download from Homepage URL, then a couple weeks/months down the road, someone will open an issue/PR that Calibre download is too slow.

---

Anyway, with the current state of `livecheck` and rate of both manual & automated PR contributions, the timeframe that the Cask remains broken is small and would probably be resolved in less than a day.

For fastest fix, maintaining a CI action that detects new Calibre update and the runs an automatic bump-cask-pr would get the issue fixed in a short period of time. As automated merges are disabled (I think due to security issues), this is probably going to be within a few hours when a maintainer can review.

**Comment by jtbayly** [comment]
Agreed that those two solutions both seem bad. 

I wonder if there are other places online that host free downloads and are neither slow nor suddenly 404 the file.

**Comment by SMillerDev** [comment]
Can't you ask the maintainers to stop removing the github hosted files? They don't disappear by themselves.

**Comment by jtbayly** [comment]
Done:

https://bugs.launchpad.net/calibre/+bug/1926765

**Comment by jtbayly** [comment]
Hmm... 

1. He says that the speed issue has been fixed. I just tested and I can confirm that it used to be consistently *very* slow, and that I just downloaded from the main server at several megabytes per second over wifi. It's a big improvement.
2. He also says, "Why not simply have a backup URL to the primary download location, which
is tried if github fails." I'm personally not familiar enough with brew or casks to know whether this is possible. Is it?

**Comment by carlocab** [comment]
> 2. He also says, "Why not simply have a backup URL to the primary download location, which
>    is tried if github fails." I'm personally not familiar enough with brew or casks to know whether this is possible. Is it?

If it were simple, we'd already be doing it. See #10241. However, if you'd like to implement this functionality, we'd be happy to review a PR.

**Comment by jtbayly** [comment]
Hey, I'm just asking. It hadn't occurred to me, and it seemed like a great suggestion. Now I know it isn't possible (yet) in homebrew. That's ok. 

Perhaps we should consider switching back to the official server, though, given the speed increase? I'm not sure it's as fast as Github, but it seems like it's worth checking.

**Comment by carlocab** [comment]
> Hey, I'm just asking. It hadn't occurred to me, and it seemed like a great suggestion. Now I know it isn't possible (yet) in homebrew. That's ok.

No worries, that was more a reaction to "simply have a backup URL" -- which weren't your words. Seems to me that it's much simpler to just not to go out of one's way to delete old release artefacts when making a new release, but I guess Calibre's maintainer and I have different ideas of what "simple" means.

> Perhaps we should consider switching back to the official server, though, given the speed increase? I'm not sure it's as fast as Github, but it seems like it's worth checking.

Might be worth doing. Feel free to open a PR for review.
