### ISSUE TITLE
Question: cask version of rclone (and other deprecated/limited formulae)

### ISSUE THREAD

**Issue by brettferdosi** [Homebrew/homebrew-cask#106519]
In the wake of PR https://github.com/Homebrew/homebrew-core/pull/64491, which deprecated formulae that rely on FUSE because it is an external dependency that went closed-source, `rclone` does not include support for mounting drives (which is the part that relies on FUSE) when installed from the formula, even when FUSE is manually installed as an external dependency (see https://github.com/rclone/rclone/issues/4775).

I made a cask version of `rclone` that downloads fully featured binaries from the project's GitHub releases page and also includes the `macfuse` cask as a dependency: https://github.com/brettferdosi/homebrew-tap/blob/main/Casks/rclone-cask.rb. I am making this issue so that others who might find this useful can see it, and I am also wondering whether the main cask tap might accept this kind of cask.

**Comment by vitorgalvao** [comment]
> and I am also wondering whether the main cask tap might accept this kind of cask.

No, thank you. For now yours is a random fork which [isn’t notable enough](https://github.com/Homebrew/brew/blob/master/docs/Acceptable-Casks.md#rejected-casks):

> + The Cask is too obscure. Examples:
>   + An app from a code repository that is not notable enough (under 30 forks, 30 watchers, 75 stars).
>   + [Electronic Identification (eID) software](https://github.com/Homebrew/homebrew-cask/issues/59021).

We want primary sources.

**Comment by brettferdosi** [comment]
Hi Vitor, thanks for the reply. I think there may have been a miscommunication. My cask does not install a fork of `rclone` - it installs binaries from the project's GitHub releases page. `rclone` is a widely used tool (https://github.com/rclone/rclone). I made the cask because the version of `rclone` built by the formula is not fully featured, but the binaries that the project releases are. I was unsure whether it would be considered for the main cask tap only because there is a formula for rclone in homebrew-core (but, as I said, it is not fully featured).

**Comment by vitorgalvao** [comment]
Indeed, I misunderstood, thank you for clarifying.

We still don’t want the cask, though. We went to great lengths to reduce the deduplication between HB and HBC and don’t want to bring it back.

And yes, I understand these aren’t exactly the same, but they aren’t sufficiently different either.

**Comment by darthShadow** [comment]
Would it be possible to remove the rclone formula altogether and just have it as a cask, that installs the official release and depends on macfuse? Is there any benefit that we get from having it as a cask?

I am enquiring about this possibility because running rclone with mount capabilities is a common use-case on Mac and we (the rclone team) get numerous issues and help threads for its absence where we need to explain to the users to just use the official releases instead of installing it via homebrew.

**Comment by carlocab** [comment]
There is a third-party tap that allows you to install an `rclone` formula with FUSE support: https://github.com/gromgit/homebrew-fuse

**Comment by darthShadow** [comment]
I would prefer that we can come to some kind of agreement that doesn't involve using third-party taps, especially since it still doesn't solve the problem of the default brew install being only partial in terms of the features.

**Comment by carlocab** [comment]
Having it as a formula is much preferable to a cask, since the formula also installs the manpage and shell completions. [*] I'd really also rather not make the confusion between casks and formulae worse by turning something that should be a formula into a cask.

[*] Of course, there is nothing in principle that stops a cask from installing manpages and completions, it's just that the functionality in `brew` to do so isn't there. Maybe someone can work on putting that in, but it's not clear that it's something we'd want, since these are usually things that come with CLI-only software, and those shouldn't be casks.

**Comment by darthShadow** [comment]
Btw, another point to it being provided as a cask is that rclone now also has the auto-update functionality which I think is more inclined towards casks rather than formulae?

Anyway, thanks for the inputs. Let me check with the team and see if we want to do anything else with this or live with the current set of restrictions.

**Comment by brettferdosi** [comment]
FWIW, the cask I made already handles the manual page provided in rclone's releases. I just did a quick read of the Cask Cookbook and it seems like a postflight stanza could be used to generate and install the completions. It would need some cleanup and review but may be a useful starting point.

**Comment by darthShadow** [comment]
That seems like a good solution, if possible.

@carlocab Would that be acceptable and would also trigger the move from rclone as a formula to a cask or do we require anything else too? I know it's not the ideal solution per Homebrew but it seems like the best possible compromise right now.

**Comment by carlocab** [comment]
I think I ordered my objections wrong. This is much more important:

>I'd really also rather not make the confusion between casks and formulae worse by turning something that should be a formula into a cask.

**Comment by darthShadow** [comment]
Any chance rclone could be treated as an exception to the rule? I **really** don't want to suggest multiple ways to install the software with each having different compromises (partial on Homebrew, unofficial on the tap).

**Comment by carlocab** [comment]
What's the harm in unconditionally recommending an external tap? Other projects don't have any qualms about recommending their own (and occasionally trash the Homebrew/core formula for good measure as well).

I would suggest you recommend the @gromgit's tap, though (assuming this is okay with them). There are already a number of fuse-dependent formulae there, and it's much easier for users to just have to look in one place when they want something with fuse support.

**Comment by darthShadow** [comment]
The aim is to simplify the process as much as possible which is why I want to get the full-featured rclone available in Homebrew itself so folks don't have to go searching for the correct tap to use.

If it comes to the point that users need to go to the rclone website to find the recommended tap, then we have already made it too complex and at that point, it's easier to just ask them to download the official release via the one-liner install command. Any future updates can also be handled via the new built-in `selfupdate` command.

**Comment by SMillerDev** [comment]
> The aim is to simplify the process as much as possible which is why I want to get the full-featured rclone available in Homebrew itself so folks don't have to go searching for the correct tap to use.

Since rclone's requirements conflict with the homebrew requirements for repositories this is not likely going to happen. The separate tap could also be a oneliner: `brew tap gromgit/fuse && brew install rclone`

**Comment by brettferdosi** [comment]
As a user of rclone, my first instinct was to grab the core formula. I was surprised to find that it doesn't support mounting, which is one of my primary use cases. This is what made me create the cask that does. I imagine many others run into the same issue and work around it by manually downloading the rclone release, which is not ideal if you want to script your machine setup.

It seems to me that, while rclone is a command line tool, its macfuse dependency does make it better suited to a cask. As a cask, it can be installed with all of its features and an automatic dependency on the macfuse cask. While it may be more elegant as a formula, it's lacking a significant feature, and because of Homebrew policies, a fully-featured formula can't be accepted first-party. Even with the third-party formula linked above that does include fuse support, if I'm reading it correctly, when you don't have macfuse installed it tells you to install the macfuse cask manually before proceeding...

Someone could host a third-party cask for rclone - I plan to use mine in the absence of a first-party one - but that would make things more confusing for users, especially if the limited first-party formula sticks around. I think the best option is to replace the core formula for rclone with a first-party cask.
