### ISSUE TITLE
livecheck for adobe-acrobat-reader shows wrong version

### ISSUE THREAD

**Issue by tiiiecherle** [Homebrew/homebrew-cask#108177]
Hey,

brew livecheck has the following output for adobe-acrobat-reader:

```
brew livecheck --cask --newer-only adobe-acrobat-reader --quiet
adobe-acrobat-reader : 21.005.20048 ==> 21.005.20054
```

Using the output for a bump gives the following error:

```
brew bump-cask-pr adobe-acrobat-reader --version=21.005.20054 --no-browse
==> Downloading https://ardownload2.adobe.com/pub/adobe/reader/mac/AcrobatDC/210

curl: (22) The requested URL returned error: 404
Error: Failed to download resource "adobe-acrobat-reader"
Download failed: https://ardownload2.adobe.com/pub/adobe/reader/mac/AcrobatDC/2100520054/AcroRdrDC_2100520054_MUI.dmg
```

Trying to download the latest version manually downloads 21.005.20048, not 21.005.20054.

It would be nice if the livecheck could be fixed.

Thanks in advance.

**Comment by bevanjkay** [comment]
@tiiiecherle 
I was having a look at this yesterday. 

I think the trouble is that the latest version is 0054, however it is only a hot fix. From what I can see there is no bundled download available and it is only a patch. 

Livecheck sees the latest version correctly, however the issue is that upstream haven't compiled an installer for that version. 

I could not find an immediate solution yesterday.

**Comment by tiiiecherle** [comment]
@bevanjkay Thanks for looking into it. I could not solve it myself either. If there is a chance to get the livecheck from somewhere else (where only the available download versions are stored) it would be nice if the livecheck could be updated. If that is not possible I guess the issue can be closed.

Thanks

**Comment by bevanjkay** [comment]
@tiiiecherle This is now resolved as the Acrobat Reader app has received an update. In future it would be nice to be able to update the livecheck to skip these edge-cases, however requires Homebrew/brew#11675 to be resolved.
