### ISSUE TITLE
Cask 'java' is unreadable: undefined method `release' for OS::Mac:Module 

### ISSUE THREAD

**Issue by helio-silva** [Homebrew/homebrew-cask#113394]
### 

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

### Description of issue

Error related to  java

Warning: Unexpected method 'license' called on Cask java.

### Command that failed

brew doctor

### Output of command with `--verbose --debug`

<details><summary>Click to expand</summary><pre><code>

helio@helio Downloads % brew doctor -v -d              
Warning: Unexpected method 'license' called on Cask java.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'java' is unreadable: undefined method `release' for OS::Mac:Module
/usr/local/Caskroom/java/.metadata/1.8.0_92-b14/20160705170140.500/Casks/java.rb:55:in `block in load'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:63:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:63:in `config='
/usr/local/Homebrew/Library/Homebrew/cask/cask.rb:50:in `initialize'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `new'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:43:in `cask'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:87:in `cask'
/usr/local/Caskroom/java/.metadata/1.8.0_92-b14/20160705170140.500/Casks/java.rb:1:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in `load'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:45:in `block in casks'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `map'
/usr/local/Homebrew/Library/Homebrew/cask/caskroom.rb:39:in `casks'
/usr/local/Homebrew/Library/Homebrew/cmd/doctor.rb:51:in `doctor'
/usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
</code></pre></details>

### Output of `brew doctor --verbose`

<details><summary>Click to expand</summary><pre><code>
brew doctor -v   
Warning: Unexpected method 'license' called on Cask java.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
Error: Cask 'java' is unreadable: undefined method `release' for OS::Mac:Module

</code></pre></details>

### Output of `brew tap`

<details><summary>Click to expand</summary><pre><code>

homebrew/cask
homebrew/core
homebrew/services

</code></pre></details>

**Comment by cho-m** [comment]
Some extra notes:
- Same issue as #89818
- Cask `java` was removed from `homebrew-cask`. If you need Java, your options are:
  - Use a Formula. You can track latest Java via `openjdk` Formula or `java` Formula Alias, or use a specific version like `openjdk@8`
  - Use a maintained Cask built by a company like Oracle (`oracle-jdk`), Eclipse (`temurin`), Azul (`zulu`), Microsoft (`microsoft-openjdk`), etc.
- What probably happened is:
  1. You installed `java` Cask a while back (you have 1.8.0_92-b14 from 2016).
  2. `brew` removed support for `license` keyword.
  3. You ran `brew update` and got newer `brew` without that keyword.
  4. Due to issue in #62223, the old leftover Cask has broken some basic `brew` commands.

---

As other maintainers mentioned, the solution is to remove the old Cask.

It is odd that you can't find directory since your logs show it:
```
/usr/local/Caskroom/java/.metadata/1.8.0_92-b14/20160705170140.500/Casks/java.rb:1:in load' /usr/local/Homebrew/Library/Homebrew/cask/cask_loader.rb:72:in instance_eval'
```

Maybe you did delete directory (or ran some command that did delete it) at some point between posting issue and running `ls` command?
