### ISSUE TITLE
dbeaver-community updates while has self updater

### ISSUE THREAD

**Issue by daniel-white** [Homebrew/homebrew-cask#134258]
### Verification

- [X] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [X] I have retried my command with `--force`.
- [X] I ran `brew update-reset && brew update` and retried my command.
- [X] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [X] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [X] I made doubly sure this is not a [checksum does not match](https://docs.brew.sh/Common-Issues#cask-checksum-does-not-match) error.

### Description of issue

I have `dbeaver-community` installed. It has an autoupdated that fights with the cask. Should the cask turn off homebrew's updating mechanism for itself (so that it requires `--greedy`)?

The update process from dbeaver itself would be preferable as it keeps it in the Dock and I don't have to retrust it on first launch.

### Command that failed

brew update

### Output of command with `--verbose --debug`

```shell
N/A configuration problem with dbeaver-community
```

### Output of `brew doctor --verbose`

```shell
N/A configuration problem with dbeaver-community
```

### Output of `brew tap`

```shell
N/A configuration problem with dbeaver-community
```

**Comment by p-linnane** [comment]
Fixed in https://github.com/Homebrew/homebrew-cask/pull/134260.

**Comment by daniel-white** [comment]
@p-linnane thanks!

**Comment by spencermathews** [comment]
For context, the `auto_updates` stanza was  added in #118207 and removed in #125370.

The rationale is that DBeaver does not actually auto-update. It checks for and downloads updates but it does not actually install them. So the Cask does not meet the criteria from the [Cask Cookbook](https://docs.brew.sh/Cask-Cookbook) to "use [auto_updates] if Check for Updates… or similar is present in app menu, but not if it only opens a webpage and does not do the download and installation for you."

It would be really nice if DBeaver would implement a complete auto-update mechanism, but until then there is bound to be some compromise (here meaning manual intervention). Pick your poison: drag and drop an installer or approve on first launch (fortunately DBeaver is [signed](https://support.apple.com/en-us/HT202491)). At least the latter is consistent with other Casks that do not auto-update.

Unless the maintainers would like to change or clarify best practices for handling situations like this, I suggest that #134260 be reverted since DBeaver does not, at present, qualify as an auto-update Cask.

As for `N/A configuration problem with dbeaver-community` issue, @daniel-white and @p-linnane since the message is pretty vague can we be certain `auto_updates` (or lack thereof) is the culprit? I have been using this Cask for some time and never experienced any conflict despite there being two possible update routes.

**Comment by daniel-white** [comment]
Thanks @spencermathews for your insight. I forgot to search for the history. I suppose `does not do the [...] installation for you.` is the part that is missing only. it does do the download, but it does force you to use Finder to do the drag and drop bit.

* is there something the cask system can do to avoid removing it completely from the dock? thats my biggest gripe
* is there something that Homebrew or the cask system to allow this to be configurable from the `brew` command?
* perhaps this cask needs some documentation in itself to avoid this sort of thing in the future

**Comment by p-linnane** [comment]
This may warrant a [`caveat` stanza](https://docs.brew.sh/Cask-Cookbook#stanza-caveats).

You can run `brew outdated --greedy` for the full list and the individually run `brew upgrade --cask foo` to upgrade that individual cask.
