### ISSUE TITLE
Remove appcast checkpoints?

### ISSUE THREAD

**Issue by commitay** [Homebrew/homebrew-cask#48051]
Refs: https://github.com/Homebrew/homebrew-cask/pull/47728, https://github.com/Homebrew/homebrew-cask/issues/38376, https://github.com/Homebrew/homebrew-cask/issues/43605, https://github.com/Homebrew/homebrew-cask/issues/41240 and others

This has been discussed briefly in a few places, opened this for a proper discussion.

This would basically be as the title says, the `checkpoint` string would be removed along with the `_appcast_checkpoint` command while keeping the `appcast` URL that can be parsed with external scripts/tools.

cc @brianmorton @colindunn @gtmgianni @leipert People that use their own scripts/tools for cask updates.

Would also like to know what other contributors think about this so please feel free to comment.

**Comment by leipert** [comment]
Thanks for pinging me!

Are they used for anything relating to security? If not, remove them! It makes no sense for the casks which @jcbot updates. I always check against the version string, if we need updates and not against the hash of the URL.

**Comment by gtmgianni** [comment]
Although my scripts rely entirely on the appcast `checkpoint`, I don't think using the `checkpoint` is a long term solution for updating casks. This is mainly due to the fact that there are so many casks with outdated `checkpoint` hashes, that don't actually need a version bump.

I have a blacklist of around 1000 casks that fall into this category, although by the time I run the script which scrubs the blacklist of any invalid entries (i.e. casks whose `checkpoint` hashes have changed yet again), that number decreases to around 700. In an ideal scenario, all ~300 of those casks that were removed from the blacklist would need a version bump, but in reality many of them are just unstable appcasts which get added back to the blacklist with their new `checkpoint` hash once I've manually checked them.

I think removing the `checkpoint` is something we should consider because many appcasts are unstable.

I like the idea of tailored code for each cask being used to find the latest version, as discussed in https://github.com/Homebrew/homebrew-cask/issues/41240. Out of curiosity, would we have some sort of bot which automatically submits the PRs, or would different contributors be able to update the casks themselves? If the latter is the case, how would we avoid pull request duplicates?

**Comment by vitorgalvao** [comment]
My initial idea:

* Have the tailored update code for each cask, and store it in a different repo.
* Have a bot that submit the PRs.
* In `cask-repair`, blacklist casks that are updated by the bot.

Since a huge chunk (the majority?) of submissions use `cask-repair`, blacklisting should be reasonably effective. Eventually, this would mean blacklisting every cask with `appcast` and ultimately every cask would have some kind of appcast (since code is tailored for each, there are no restrictions).

This means that in time the bot would do every version bump, with humans fixing problems in the casks themselves and the updating mechanism.

**Comment by brianmorton** [comment]
Thanks for the ping.

I do have an [issue](https://github.com/brianmorton/cask-automation/issues/4) on my own tool's github to basically throwaway the current version of appcast in favor or something tailored to each cask that I would keep on my side (eg. outside HBC)... but it is still an issue an not yet implemented.

All of my current automated scanning relies on url/version sniffing, since I found the appcasts to be a terrible signal-to-noise ratio (as well summarized by @gtmgianni ) as they currently exist.

I would support any move towards automated maintenance/updates of casks.

**Comment by commitay** [comment]
https://github.com/Homebrew/brew/pull/4310

**Comment by brianmorton** [comment]
Somewhat ironically, yesterday and today I have implemented a local sqlite database and have resumed appcast scanning (using cityhash instead of the appcast checkpoints) on my side...

**Comment by reitermarkus** [comment]
I'm against removing them until we have an actual alternative.

**Comment by commitay** [comment]
We benefit from removing them _now_ as we can add appcasts to everything that can then be used by the current scripts/tools in use by contributors, waiting means removing _more_ appcasts.

**Comment by reitermarkus** [comment]
> used by the current scripts/tools in use by contributors

I would still like to see an official tool before we remove the checkpoints.

**Comment by commitay** [comment]
I don't see any reason to wait for an offical tool to be implemented.

**Comment by reitermarkus** [comment]
> I don't see any reason to wait for an offical tool to be implemented.

And I don't see any reason to remove it when an alternative does not exist yet.

**Comment by commitay** [comment]
> A checkpoint is still more useful than *nothing*.

A checkpoint that changes without a version bump is not useful. An unstable appcast that has been removed is not useful.

**Comment by commitay** [comment]
> Right now, my only interaction with `appcast`s is having them fail in Travis and having to fix them manually.

👏  💯 

Also, I see `checkpoint`s as a hinderance to implementing the update tool as currently appcasts are required to be stable, whereas the purpose of the new tool would be to remove this restriction. I think keeping the checkpoint means we are limiting what appcasts we have available to build and test the tool with.

Removing them would also somewhat simplify implementation of a `cask-repair` command (https://github.com/Homebrew/homebrew-cask/issues/48086) as the checkpoint wouldn't need to be checked and/or updated.

**Comment by commitay** [comment]
Removed another appcast: https://github.com/Homebrew/homebrew-cask/pull/48263

**Comment by brianmorton** [comment]
To reiterate, I support @commitay and @vitorgalvao in removing the CHECKPOINTS - the appcast URL is still valuable.

**Comment by brianmorton** [comment]
@leipert its ok for me?
```
$ brew cask audit --download rubymine
==> Downloading https://download.jetbrains.com/ruby/RubyMine-2018.1.3.dmg
########                                                                  12.1%
```

```
$ brew config
HOMEBREW_VERSION: 1.6.8-25-g9b21422
ORIGIN: https://github.com/Homebrew/brew
HEAD: 9b21422b72475068f2c139bc5677bfd43aa68995
Last commit: 8 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 4fbabc99fcf13f3e82254fec472f1fee896cbf3f
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_LINKAGE_CACHE: 1
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3_2/bin/ruby
Clang: 9.1 build 902
Git: 2.17.1 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Java: N/A
macOS: 10.13.3-x86_64
CLT: 9.3.0.0.1.1521514116
Xcode: 9.3.1
XQuartz: N/A
```

**Comment by MikeMcQuaid** [comment]
@leipert Run `brew update` again.

**Comment by leipert** [comment]
@brianmorton / @MikeMcQuaid: Won't help, as I am on brew stable:
```
$ brew config
HOMEBREW_VERSION: 1.6.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3081390ff845a6172b9004cf404c3e028e3be745
[...]
$ brew update
$ brew config
brew config
HOMEBREW_VERSION: 1.6.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: 3081390ff845a6172b9004cf404c3e028e3be745
[...]
```
