### ISSUE TITLE
Add `upgrade` `--greedy` explanation to FAQ.

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#48181]
We should add that explanation to the [FAQ](https://github.com/Homebrew/homebrew-cask/tree/master/doc/faq), including *why* it works that way.

It’s incredibly tiring and frustrating to keep answering the same question from people who don’t make an effort to search issues or read the `man` page. We need a document somewhere we can link people to.

**Comment by wfdd** [comment]
I think it'd be more effective if `brew cask <command> --help` quoted the corresponding section from the man page rather than erroring out with 'help does not take arguments'.  People are not too accustomed to looking at man pages nor would they think to look for a twice-nested FAQ that's not linked to from the readme.

**Comment by amyspark** [comment]
@wfdd - `help does not take arguments` is a bug (certainly leftover from one of my Cask fixes). Can you file a report about it?
