### ISSUE TITLE
how to handle casks that *MAY* be outdated?

### ISSUE THREAD

**Issue by brianmorton** [Homebrew/homebrew-cask#49026]
I am speaking specifically about the `fricas` cask here, but I have noticed it in the past as well.

Our current version for it is `1.2.6`, however they have had releases up to the current one (`1.3.4`). It is not clear if these would work on mac, however, so I understand why the cask is still on `1.2.6`.

Since this is so far out of date with their latest release, is there a way to indicate this on the cask? To be clear, I am not sure if the more current releases can be run on macOS or not, but the specific url/binary that used to work for mac releases no longer does.

**Comment by vitorgalvao** [comment]
It’s been three years since the last release. If this had been the last release at all, it’d be fair to keep it around. But since it’s the last version on macOS, it means those are no longer being maintained and might contain serious flaws, meaning it might be wise to remove them.

We have a kind of precedent (I think it’s documented) with MAS apps. If the MAS version is beyond the direct-download version, we remove it.

**Comment by brianmorton** [comment]
It's not clear if this no longer works on macs, or if they just moved to a different release model and nobody has bothered to look into if it can be made to work with on macOS... but that may indirectly validate what you're saying: since nobody has cared to try since then it may be worth removing?
