### ISSUE TITLE
vulkan-sdk: need stable directory to add to PATH

### ISSUE THREAD

**Issue by gibfahn** [Homebrew/homebrew-cask#51330]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#checksum-does-not-match-error) error.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

As detailed in `brew cask info vulkan-sdk` (see below), using the SDK requires that the relevant directories be added to the `PATH` and `LIBRARY_PATH`. However as the cask is only installed into the caskroom, this means that the path to be added (`/usr/local/Caskroom/vulkan-sdk/1.1.82.0`) includes the version, and thus when `brew upgrade` installs a new version, the user's environment variables become out-of-date.

I can think of a couple of ways to fix this, so wanted to get feedback on what the idiomatic solution for homebrew-cask was before trying to raise a PR.

1. Change the suggested `export` commands to dynamically guess the latest version:
  ```bash
  # This is pretty hacky, and won't work if the user explicitly wants to `brew link` an older version.
  VULKAN_SDK="$(echo /usr/local/Caskroom/vulkan-sdk/* | sort -V | tail -1)"/macOS

  export DYLD_LIBRARY_PATH="$VULKAN_SDK/lib:$DYLD_LIBRARY_PATH"
  export VK_ICD_FILENAMES="$VULKAN_SDK/etc/vulkan/icd.d/MoltenVK_icd.json"
  export VK_LAYER_PATH="$VULKAN_SDK/etc/vulkan/explicit_layer.d"
  export PATH="$VULKAN_SDK/bin:$PATH"
  ```
2. Create a symlink called `current` or `latest` to represent the currently installed version
  ```bash
  # brew cask install vulkan will do something like:
  ln -sf /usr/local/Caskroom/vulkan-sdk/1.1.82.0 /usr/local/Caskroom/vulkan-sdk/current
  ```
3. Move `vulkan-sdk` from a Cask to a non-cask, it's a command-line tool anyway.
  - This would probably involve symlinking binaries into `/usr/local/bin`, and libraries into `/usr/local/lib`. I'm not sure that this would provide a good solution for the `VK_LAYER_PATH` issue.

<br/><br/>

```console
$ brew cask info vulkan-sdk
Cannot read termcap database;
using dumb terminal settings.
vulkan-sdk: 1.1.82.0
https://vulkan.lunarg.com/sdk/home
/usr/local/Caskroom/vulkan-sdk/1.1.82.0 (202 files, 582.4MB)
From: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/vulkan-sdk.rb
==> Name
LunarG Vulkan SDK
==> Artifacts
/usr/local/Caskroom/vulkan-sdk/1.1.82.0/macOS/bin/vulkaninfo (Binary)
==> Caveats
You must define a few environment variables for this SDK to work:
  export VULKAN_SDK=/usr/local/Caskroom/vulkan-sdk/1.1.82.0/macOS
  export VK_ICD_FILENAMES=/usr/local/Caskroom/vulkan-sdk/1.1.82.0/macOS/etc/vulkan/icd.d/MoltenVK_icd.json
  export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/usr/local/Caskroom/vulkan-sdk/1.1.82.0/macOS/lib
  export VK_LAYER_PATH=/usr/local/Caskroom/vulkan-sdk/1.1.82.0/macOS/etc/vulkan/explicit_layer.d

Installing vulkan-sdk means you have AGREED to the license at
  https://vulkan.lunarg.com/sdk/home#sdk-license

To use vulkan-sdk, you may need to add the /usr/local/Caskroom/vulkan-sdk/1.1.82.0/macOS/bin directory
to your PATH environment variable, eg (for bash shell):

  export PATH=/usr/local/Caskroom/vulkan-sdk/1.1.82.0/macOS/bin:"$PATH"
```

**Comment by vitorgalvao** [comment]
> 3. Move `vulkan-sdk` from a Cask to a non-cask, it's a command-line tool anyway.

Is it open-source?

**Comment by gibfahn** [comment]
>Is it open-source?

I'm actually finding it quite hard to work this out 😁 (I only learned about this SDK today).

[This](https://www.lunarg.com/lunarg-releases-vulkan-sdk-1-0-69-0-for-mac/) suggests it is, as does [this](https://www.lunarg.com/vulkan-sdk/). The license is Apache 2. However I can't work out how you actually download the source.

<img width="762" alt="image" src="https://user-images.githubusercontent.com/15943089/44684789-e0728d80-aa41-11e8-9248-6d4d539f3ea4.png">

<img width="731" alt="image" src="https://user-images.githubusercontent.com/15943089/44684800-e9fbf580-aa41-11e8-8c5f-687a64c5fc4f.png">

Why do you ask? Is Cask for non Open-Source things? I always thought Cask was for things that went into `/Applications` and other non-standard places (i.e. not `/usr/local/bin`), and things that had GUIs (like `meld`).

**Comment by vitorgalvao** [comment]
> Why do you ask?

If it’s open-source and CLI-only, it goes into Homebrew. Everything else goes into Homebrew-Cask. We enforce this division [in the spirit of deduplication](https://github.com/Homebrew/homebrew-cask/issues/15603).

**Comment by vitorgalvao** [comment]
https://github.com/Homebrew/homebrew-cask/pull/52782

**Comment by apenngrace** [comment]
Isn't something better than nothing?  Why not offer an imperfect cask until the time somebody submits a Homebrew formula?

This was not simply a command line tool, it is a software library for a next-generation graphics API.  This should have been supported by Apple, which had supported other Khronos APIs like OpenGL, OpenGL ES, OpenCL, etc.  Mac is now officially supported only because Khronos made this happen without Apple's help.

I originally submitted this as a cask because LunarG (which is some part of the video game company Valve) started releasing builds for Mac earlier this year.  LunarG versions their binary builds, but if you want to build from source, they do not release a single tarball all within a single build system.  Each project that contributes to the overall release from about a half dozen repos, some versioned, some not (just a particular commit).  

Perhaps this belongs in a thread in the Homebrew message boards, but I am somewhat of a newbie creating formulae and I'm not sure this build would be done in homebrew.  Would a single formula pull together all the sources and then run various builds?  Or would there have to be half a dozen formulae, none of which stand alone, then code copied around to a final release directory?

Just in case, I even submitted a question to LunarG if they plan to unify their build process and put out a single source release to make it easier to build.  Their response was that they've discussed it, but so far it has not happened.

It seems a shame to currently not offer vulkan at all on homebrew.  As a programmer, homebrew is the first place I look when I want to install software libraries.

**Comment by vitorgalvao** [comment]
> Isn't something better than nothing?

Not really, because it means extra maintenance burden.

> Why not offer an imperfect cask until the time somebody submits a Homebrew formula?

Because that’ll never happen otherwise. It’d stay forever as the imperfect cask. We either commit to deduplication or we don’t.

> It seems a shame to currently not offer vulkan at all on homebrew.

You may wish to consider hosting your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md) for it. Not being available in the main repos does not prevent the cask from existing.

**Comment by vitorgalvao** [comment]
@apenngrace I’m sympathetic to your case, but I doubt this is used by enough people to warrant the trouble (would have to check the analytics).

There won’t be a “for the time being”. If it’s readded it’ll be here indefinitely, and when it can be removed you/other users of this will likely no longer care/remember to remove the cask, leaving it as an extra thing for maintainers to care for for little gain. You haven’t solved any of my worries of the previous comment.

Again, you’re free to maintain your own tap if you need this as a cask.

**Comment by apenngrace** [comment]
I'm trying to create my own tap for this, but I am getting errors.  I created `apenngrace/homebrew-vulkan`, but I get this error when I try to run `brew tap apenngrace/homebrew-vulkan`:

```
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/apenngrace/homebrew-vulkan/vulkan-sdk.rb
vulkan-sdk: undefined method `cask' for Formulary::FormulaNamespace2442d5c9a2b6eab860b9626a76962c34:Module
Error: Cannot tap apenngrace/vulkan: invalid syntax in tap!
``` 

I'm not sure what do to fix this.  I've tried adding the line `require 'cask/all'` at the top of the file and that does not seem to matter either.

**Comment by vitorgalvao** [comment]
@apenngrace It needs to be inside a `Casks` directory. Sent PRs to fix it.

**Comment by apenngrace** [comment]
@vitorgalvao, today I worked my `apenngrace/homebrew-vulkan` tap and I was wondering if you could provide feedback on it.  I have a number of comments/questions:

- Is there a way to use the `FileUtils` API in order to specify things like `sudo:true` when trying to create directories in folders like `/etc/`.  For those, I used system_command, and I'm wondering if that is the best way when `sudo` is needed.
- There are a number of files that I modify using the JSON API.  I am modifying files because there are relative paths such as "../../../lib/libvulkan.dylib" that are no longer valid when referenced from a symlink (rather than the directory structure of the decompressed tarball).  I change the path to the absolute path in the brew cellar for the library.  Is there any recommendations when doing such patches?
- I use Dir.glob a number of places to get arrays of filenames, then I work with those file names in loops.  I noticed that other casks rarely do things like this.  Is it preferred to just enumerate every file explicitly in the cask even though it may be repetitious?
- I noticed that if I try to call a method outside of the cask object, brew displays warnings.  Is there a better way, or should that just be avoided and make the code repetitive if necessary?

Thanks for you help.

**Comment by vitorgalvao** [comment]
@apenngrace You can use whatever ruby code you want inside casks. We try to not have casks be too convoluted for practical reasons (maintainability and auditability). On a personal tap, do whatever works.
