### ISSUE TITLE
Teaching users about bypassing Gatekeeper without turning it off?

### ISSUE THREAD

**Issue by vitorgalvao** [Homebrew/homebrew-cask#51490]
Refs https://github.com/Homebrew/homebrew-cask/issues/48862#issuecomment-404338730.

Now that quarantining has landed, we’re bound to get some users that will get annoyed by and disable Gatekeeper. That is unnecessary, because if you set it to only allow opening apps from the app store and identified developers, you can still bypass Gatekeeper by right-clicking and selecting “Open”. It makes perfect sense, as macOS understands you’re making a deliberate decision.

![gatekeeper](https://user-images.githubusercontent.com/1699443/42603940-f08f977a-8567-11e8-9585-987fb3015019.gif)

Should we talk about this method somewhere in the documentation?

**Comment by claui** [comment]
On the one hand, this feature is completely under Apple’s control, and Homebrew/HBC shouldn’t feel responsible for documenting it. There’s a small risk that documenting it will blur the lines about who actually controls the feature.

On the other hand, leaving the user in the rain with that problem is not really an option. Also, adding Gatekeeper support was a deliberate action on our side so we’re kinda in the same boat after all.

So yes, we probably should mention it in the docs, and also include a link to Apple’s [About Gatekeeper](https://support.apple.com/en-us/HT202491) article.

**Comment by vitorgalvao** [comment]
Done in #51573.

**Comment by fakirmedia** [comment]
Who does that? I love homebrew and cask, because I can use my mouse less. I use spotlight or alfred to open an application I installed with cask, no symbols but through finder, no right clicking. Is there a way to disable the gatekeeper dialog without deactivating gatekeeper completely? Or at least a way to select "open" with the keyboard?

**Comment by vitorgalvao** [comment]
> I use (…) alfred

In that case, I have two Workflows for you.

> Is there a way to disable the gatekeeper dialog without deactivating gatekeeper completely?

[`RemoveQuarantine`](https://github.com/vitorgalvao/alfred-workflows/#removequarantine-).

> Or at least a way to select "open" with the keyboard?

[`RightClick`](https://github.com/vitorgalvao/alfred-workflows/#rightclick-).
