### ISSUE TITLE
[DISCUSSION] UX & Command Removal/Merging with Homebrew

### ISSUE THREAD

**Issue by j0hnm4r5** [Homebrew/homebrew-cask#53143]
This is continuing off the discussion in #53045.

The removal of `brew cask search` makes sense, in that it was an attempt to reduce the number of commands maintainers of homebrew-cask have to support, especially considering that the command itself duplicated functionality provided by the standard `brew search`.

I can even get behind the argument that the removal of that command does in fact help the end-user, in that they no longer have to remember to use a different command to search for normal brew apps and cask apps. In a vacuum, it was a good idea.

But in practice we're left with a fragmented system, where users must now remember two sets of commands `brew` and `brew cask`, and remember when to use which command, which is a **huge** issue with UX. Right now, this issue is relegated only to `search` (as far as I know), but presumably more of cask's extraneous commands will be removed in favor of their homebrew counterparts, and the issue will become worse and worse over time.

**My proposed solution**: this is an all-or-nothing thing; we can't remove any commands until all commands can be removed at the same time. We should deprecate commands as-needed and warn users that they will be removed in the future, but continue to let them be used until every possible command is merged.

**Comment by vitorgalvao** [comment]
> but presumably more of cask's extraneous commands will be removed in favor of their homebrew counterparts

There’s no basis to presume this. Especially since casks and formulae can (and do) have the same token. There’d be no way to distinguish a `brew info transmission` to mean the cask or the formula.

> but continue to let them be used until every possible command is merged.

Which also eliminates this point.

I’m sympathetic to your plight. I sometimes still do `brew cask search`. But as is common with this types of requests, you’re considering what you want more than how it affects the underlying system. If we make `brew cask search` work again, we’ll need to add more code to separate `brew search` and `brew cask search`. We can’t simply alias the commands because it makes no sense that `brew cask search` would also search formulae but it’d also make no sense to remove casks from `brew search` at this point.

Closing the issue because the conversation fits perfectly well in https://github.com/Homebrew/homebrew-cask/issues/53045. That issue was opened exactly for this request and has not steered away from it. In the case that was your intention, I ask you do not open new issues to try to circumvent a maintainer having closed another. In those situations, please ask the maintainer to reopen it or if it’s fine for you to open a new one, in the case the conversation has steered too off course (not the case here). In those cases we’ll either reopen if new good points were made, or keep it closed if everything has already been taken into consideration and agreed upon by the maintainers.

**Comment by j0hnm4r5** [comment]
I certainly didn't open this new issue to circumvent the closed discussion over there; I even got involved in that convo after it was closed. I just think that it's a bigger issue surrounding UX, and the discussion shouldn't be about search in a vacuum.
