### ISSUE TITLE
Alternative Cask for Skype for China

### ISSUE THREAD

**Issue by hanxue** [Homebrew/homebrew-cask#54999]
Currently the Skype cask cannot be installed in China because Microsoft Azure is blocked in China

```
$ brew cask reinstall skype
==> Satisfying dependencies
==> Downloading https://endpoint920510.azureedge.net/s4l/s4l/download/mac/Skype-

curl: (7) Failed to connect to endpoint920510.azureedge.net port 443: Operation timed out
Error: Download failed on Cask 'skype' with message: Download failed: https://endpoint920510.azureedge.net/s4l/s4l/download/mac/Skype-8.33.0.41.dmg

For reference: https://www.comparitech.com/privacy-security-tools/blockedinchina/

![image](https://user-images.githubusercontent.com/760008/48525929-c3bb5880-e8c0-11e8-8fc4-c0fc2f6a474c.png)
```

## Different Version for China

If you access http://skype.com/ within China, you will be redirected to http://skype.gmw.cn

The current version of Skype, `8.33.0.41` will not work in China. There is a Chinese version of Skype, version `7.59.37`, that is available at the url http://imgskype.gmw.cn/resource/uploadimg/mac/Skype_7.59.37.dmg

As far as I understand, Homebrew Cask does not have the `mirror` Cask stanza for alternative URL. Having a condition based on geographical location will also be tricky. 

Is it still possible to add the China download URL to the `skype.rb` cask, or is it better to have a separate Cask, i.e. https://github.com/Homebrew/homebrew-cask-versions/pull/6541/commits/592ba15773a128f8db9e56bb8c7eee3ef02172ff ?

**Comment by ran-dall** [comment]
@hanxue Just a thought, I know `sudo systemsetup -gettimezone` will get the time zone. It only works on with `sudo` thought. I think maybe you could make an if...else type statement so that if the time zone matches China, then it would install the Skype from China. The only downside to this is that it requires `sudo`, as I mentioned, but [there have been some takes about how to work around that.](https://github.com/Homebrew/homebrew-cask/issues/19180#issuecomment-188522310) Just an idea, using time zones which is sort of geographic...

**Comment by ran-dall** [comment]
@hanxue I guess this has already been addressed...
[**Regional, Localized: Any version that isn’t the US English one when that exists.**](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask)
I linked it to the place in the docs where it states that.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask/pull/55063.
