### ISSUE TITLE
Cask 'inkscape' is outdated and 32 bit only

### ISSUE THREAD

**Issue by TAKeanice** [Homebrew/homebrew-cask#58034]
### Description of feature/enhancement

https://github.com/Homebrew/homebrew-cask/blob/master/Casks/inkscape.rb features version 0.92.2, although the current version is 0.92.4 . Additionally, it seems not to be the 64-bit version, so Mojave always warns me that it will be outdated soon (not optimized)

If someone needs me to build it, I would appreciate help with that, since I do not know how to do it properly. MacPorts apparently offers a formula (or however that is called in MacPorts) to build inkscape, maybe that could be of help.

**Comment by TAKeanice** [comment]
The profile (or formula) for the MacPorts build can be found here: https://github.com/macports/macports-ports/blob/master/graphics/inkscape/Portfile

**Comment by vitorgalvao** [comment]
We (Homebrew **Cask**) don’t build stuff, we download whatever upstream has. And has they mention on the page:
![image](https://user-images.githubusercontent.com/1699443/51843304-9a7c6700-230a-11e9-8662-20b8f0ee1ec7.png)

Which means we have no access to `0.92.4`. If you want to help us have that version, you need to talk to *them* (Inkscape) and help *them* build the macOS version.

**Comment by TAKeanice** [comment]
@vitorgalvao I know that you do not _host_ builds.

However, it is definitely possible to create a .dmg and host it somewhere. It does not have to be done by the people behind inkscape themselves!
This is what I offered my help with.

In a second step, the formula can be changed. As far as I understand, that is the task of some of the maintainers of that formula.

**Comment by vitorgalvao** [comment]
> I know that you do not _host_ builds.

We don’t, but that’s not what I said. I said we don’t *build*. Period.

> it is definitely possible to create a .dmg and host it somewhere. It does not have to be done by the people behind inkscape themselves!

Yes, it does. We only accept official builds (or third-party builds that the official developers officially aprove and link to). That is a security measure. We can’t accept any build from any random person.

> In a second step, the formula can be changed.

Small note, since it has been called that a lot: it’s a *cask*, not a *formula*. They behave and are constructed differently. For example, formulae can build software, while casks can’t. That is an important distinction for this conversation.

> As far as I understand, that is the task of some of the maintainers of that formula.

There are no specific maintainers for specific casks.

However you want to go about it, [what I mentioned previously](https://github.com/Homebrew/homebrew-cask/issues/58034#issuecomment-458157472) is the **only** way to have this updated: *they* need to provide the build or officially support someone who does.

> If someone needs me to build it, I would appreciate help with that, since I do not know how to do it properly.

And if you want to be that person, you still need to ask *them*, not us. If there’s someone that can guide you building *their* software, it’s *them*. We don’t build, that’s neither our task nor our goal.

**Comment by TAKeanice** [comment]
Alright, thanks for your clarification. To only accept official builds is a reasonable measure. I will try to reach some people who contribute to the Inkscape project and see if they can do something.
