### ISSUE TITLE
[bug] cask upgrade broken

### ISSUE THREAD

**Issue by bernstein82** [Homebrew/homebrew-cask#59090]
`cask upgrade` just ate an hour of my time with messages like 
```
Warning: Unexpected method 'license' called on Cask flashlight.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
```
```
Warning: Unexpected method 'gpg' called on Cask libreoffice.
Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
```
```
Error: Cask 'openzfs' definition is invalid: invalid 'depends_on macos' value: :mountain_lion
```
had to figure out how brew cask actually works (trying to execute ruby code that depends on removed functionality... wtf?), which is *not* fine btw even though i'm a software developer, and then delete/manipulate offending lines of code

**Comment by bernstein82** [comment]
well probably similar to #58046

**Comment by vitorgalvao** [comment]
> well probably similar to #58046

It’s not “probably similar to”; that is the fix.

> just ate an hour of my time with messages like

That is unfortunate and I understand your frustration. However, I’m noticing a tone that grows worse as your message progresses, and that is not OK. Realistically, you should’ve checked open issues for the bug before trying to dig into the code. That is what everyone else has done so far.

Also, you ignored the issue template that is in place, and that itself wastes maintainer time.

Finally, I’ll ask that you don’t open issues and comment on others for the same thing all at the same time.

I don’t think your first message is awful, but again, I’m detecting a tone that I’ve seen many times before, usually from people with a contributions profile similar to yours. So instead I’ll stress:

* The fix is that issue you found.
* It is unfortunate this caused you some lost time, and that was not our intention.
* This is free software, run by volunteers on their available time.
* In the future, please do fill the issue template (or, as it mentions, your issue will be closed without review).
