### ISSUE TITLE
`brew cask install` should check if app and binaries already installed 

### ISSUE THREAD

**Issue by Cyberbeni** [Homebrew/homebrew-cask#60010]
### Description of feature/enhancement

`brew cask install` should check if app and binaries already installed first instead of only after download and should allow continue with installing even if cask was already installed but the app got deleted manually

### Justification

There is no reason to waste time with downloading if we already know the app is already installed from another source, should suggest `reinstall` to the user if they want to force it.

### Example use case

Keeping installed applications on multiple devices synced through a shared config file.

**Comment by vitorgalvao** [comment]
This has been asked before.

What you’re asking would require multiple checks, before and after downloads. On the other issue, nobody was interested enough to implement it.

**Comment by Cyberbeni** [comment]
Why would it need multiple checks before and after? If cask's app artifact is missing then use reinstall, otherwise use install. I barely use ruby but I could probably make it if you want.

**Comment by vitorgalvao** [comment]
> Why would it need multiple checks before and after?

Because at the core, your ask is “do this at every step of the process”. We can’t just move the checks to happen before the download, they still need to happen after as well.

Downloading is unlikely to be a waste of time, as it may get a newer version.

Downloading may not be a waste of time because it may be a different app (beta, for example) with the same name.

Users who don’t remember having installed a piece of software manually and then try to install from HBC and don’t want it are the minority.

This request isn’t relevant for most users.
