### ISSUE TITLE
Requesting help to release CoreLocationCLI V 3.1.0

### ISSUE THREAD

**Issue by fulldecent** [Homebrew/homebrew-cask#61587]
This is an existing cask.

New version of upstream software released at https://github.com/fulldecent/corelocationcli/releases

**Comment by vitorgalvao** [comment]
[Takes only a few seconds](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

**Comment by vitorgalvao** [comment]
Wait, this was a formula before. Why did you remove the formula to make a cask? That’s backwards.

**Comment by fulldecent** [comment]
This package requires access to CoreLocation and that made me ineligible to use formulas. I tried formulas originally from the beginning. That's how I ended up here.

I started using the instructions but then it asked for my GitHub password so I stopped and requested help here.

**Comment by vitorgalvao** [comment]
> I started using the instructions but then it asked for my GitHub password

Your password is never store. Instead, a token is requested. I’m the maker of that script. [You can inspect it](https://github.com/vitorgalvao/tiny-scripts/blob/master/cask-repair). The password request is made by [`hub`](https://github.com/github/hub), which is from Github.

I expect to sometime soon chance `cask-repair` to use the API directly, instead of passing through `hub`.

All this to say that you can trust that password prompt as much as you trust Homebrew Cask.
