### ISSUE TITLE
Google Chrome Version outdated

### ISSUE THREAD

**Issue by cobour** [Homebrew/homebrew-cask#62640]
"brew cask _stanza version google-chrome" says 74.0.3729.108
actual version is 74.0.3729.131

**Comment by robertleeblairjr** [comment]
Most or all of the builds have failed on Travis for the past day or two. From the details it is failing brew cask style. Probably because of the recent update to rubocop 0.67 to 0.68. Maybe because of the change in the configuration file. There may have been more issues because not long after 0.68 was released, then there was a patch 0.68.1 released.
