### ISSUE TITLE
TinyMediaManager removes configuration

### ISSUE THREAD

**Issue by raistlin2912** [Homebrew/homebrew-cask#65562]
Every time I update the program using brew, I get removed my configuration and starts like I installed from zero. If I do the update trought the application this don't occur.

**Comment by raistlin2912** [comment]
I pinned the app until this is fixed.

**Comment by vitorgalvao** [comment]
1. Pinning doesn’t work on casks.
2. The only thing we do on upgrade is replace the old app bundle with the new one. It may be that they save the configuration inside the app bundle itself, which is atypical.

This is not a Homebrew Cask issue.

**Comment by raistlin2912** [comment]
Hello @vitorgalvao 
Yes, I see the package and the configuration is stored inside, I ask the developers of the app. I use homebrew-cask-upgrade tap for upgrades, this program CAN pin a cask to a version.

**Comment by vitorgalvao** [comment]
> I use homebrew-cask-upgrade tap for upgrades, this program CAN pin a cask to a version.

No, it can’t. Not unless they alter the permissions on the software or the software itself, which would be a red flag. What they [claim to do with pinning](https://github.com/buo/homebrew-cask-upgrade#version-pinning) is ignore the cask when you upgrade *through them*. If the software wants to auto-update (which several do), it will presumably not work, which is the whole reason we don’t have pinning in the default commands.

Also, be aware that software is not official and uses (used?) unsupported methods. Any changes you make to your setup as a consequence will not be supported by us.

**Comment by raistlin2912** [comment]
@vitorgalvao 
https://github.com/buo/homebrew-cask-upgrade#options

Third parameter starting on bottom.

**Comment by raistlin2912** [comment]
@vitorgalvao I like to ask one question before doing work on it. I localized the files inside the package that gets the configuration. Can I put a code in RB file that saves this files if exists and restore it when upgrades the cask?

Also, if the app updates well by itself, why not configure like steam for example?

**Comment by vitorgalvao** [comment]
> https://github.com/buo/homebrew-cask-upgrade#options
> 
> Third parameter starting on bottom.

Read what I posted. I [linked to what they claim to do](https://github.com/buo/homebrew-cask-upgrade#version-pinning):

> Pinned apps will not be updated by `brew cu` until they are unpinned. NB: version pinning in `brew cu` will not prevent brew cask `upgrade` from updating pinned apps.

See how they don’t even pin strongly enough to prevent upgrading from `brew cask upgrade`? That means that **if the software want to upgrade itself** (which again, many do), their pinning is unlikely to work.

> Ignores the cask yes, but in practice is the same

No, it is not the same. The fact that it isn’t is the whole reason we officially don’t support it.

> (for my needs)

For your needs *in this particular case*. It’s fine if it works for you, but please don’t say it’s the same “in practice”, because it definitely is not. We need to consider all casks, not just one.

> Can I put a code in RB file that saves this files if exists and restore it when upgrades the cask?

We’re unlikely to accept such a change at this point. Contact upstream first.

> Also, if the app updates well by itself, why not configure like steam for example?

“Like steam” how? Please be specific. Do you mean unversioned?

1. This cask can be pinned because it is (or appears to be) one of the cases that does not updated itself. I never said it did, I said *many* do.
2. Casks are versioned when they can be; they’re not only when they can’t, which happens when they have neither a versioned URL nor an `appcast`.

**Comment by raistlin2912** [comment]
Yes, I mean leaving it unversioned, but every time someone launches the command you will be losing the configuration of the application, at least until the developer of the application puts the configuration outside the APP file.

I know this is not a Cask problem, but you can give a simple solution from this repository, because the other option while neither us nor the developers of the application do something is not to install it using casks.

**Comment by vitorgalvao** [comment]
> Yes, I mean leaving it unversioned, because every time someone launches `brew cask upgrade` you will be losing the configuration of the application, at least until the developer of the application puts the configuration outside the APP file.

You’ve got that backwards. Saving configurations outside the app bundle *is the norm*. Almost no app saves the configuration inside the bundle. That is highly atypical and breaks signing. In fact, in over half a decade of maintaining HBC, I don’t remember any other app doing that.

> I know this is not a Cask problem, but you can give a simple solution from this repository, because the other option while neither us nor the developers of the application do something is not to install it using casks.

Many people (too many) try to go around limitations in software by putting workaround into casks. *That is the wrong solution* because it leaves the software deficiency upstream. And then those fixes need to be maintained, and may linger even after upstream has fixed the problem. It’s workarounds on top of workarounds, and it’s the reason the world’s software is strung together by the digital equivalent of duct tape. We prefer to do things right.

This cask isn’t popular. It can wait for upstream fixes.

```
tinymediamanager (added 1098 days ago)
30 days: 42 (#1079)
90 days: 84 (#1320)
365 days: 223 (#1550)
```

**Comment by raistlin2912** [comment]
Ok, I remove the installation from casks until the developer stores his config files on the correct location. I opened an issue in his repo.

Thanks.

**Comment by raistlin2912** [comment]
Hello @vitorgalvao This is the response from developers app: https://github.com/tinyMediaManager/tinyMediaManager/issues/488

The said basically that they don't want to change the location of configuration. Because of this I think that the best solution is remove the application from casks list, because if the developer don't want to change this behaviour and Cask repo don't want to get the app unversioned, installing this app with Homebrew-Cask is a problem.

**Comment by vitorgalvao** [comment]
> the best solution is remove the application from casks list

No. This is the solution: https://github.com/Homebrew/homebrew-cask/pull/65644
