### ISSUE TITLE
Is it ok to update a cask version by using regular git commands instead of cask-repair?

### ISSUE THREAD

**Issue by mrjayviper** [Homebrew/homebrew-cask#65718]
I was thinking of:

1. cloning the repo
2. creating a new branch
3. update the version + sha256 if available
4. git push
5. raising a merge request

**Comment by reitermarkus** [comment]
Sure, whatever is easier for you. 😉

**Comment by sjackman** [comment]
@mrjayviper You've been asked by @vitorgalvao on three occasions to ask questions on [Discourse](https://discourse.brew.sh) rather than on GitHub issues, which you've ignored, and so I'm blocking you from Homebrew for one week. Please ask questions on Discourse, and use GitHub issues for reporting bugs. When you report an issue on GitHub, please read and complete the issue template.
1. https://github.com/Homebrew/homebrew-cask/issues/65547#issuecomment-507297736
2. https://github.com/Homebrew/homebrew-cask/issues/65652#issuecomment-508082934
3. https://github.com/Homebrew/homebrew-cask/issues/65655#issuecomment-508083426
