### ISSUE TITLE
Individual Word/Excel/etc casks

### ISSUE THREAD

**Issue by joh-klein** [Homebrew/homebrew-cask#66735]
I would like to revisit/reopen #41092 and was wondering if this website would suffice as official enough to go forward and satisfy https://github.com/Homebrew/homebrew-cask/pull/41092#issuecomment-346224825.
If yes I'll get a PR on the way.

**Comment by vitorgalvao** [comment]
> if this website would suffice as official

You didn’t post a link.

**Comment by joh-klein** [comment]
Sorry. Of course: https://docs.microsoft.com/en-us/officeupdates/update-history-office-for-mac

**Comment by vitorgalvao** [comment]
That works.

Use that page as the `appcast`, not as the `homepage`, since the links they provide are from the same domain as the proper homepages.

One PR per cask. It’s fine if you want to submit just one of them to start so we can iron out the kinks before submitting the others.

Since they are `pkg`s, don’t forget [`uninstall`](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/uninstall.md).

Feel free to ping me on the PR.
