### ISSUE TITLE
move android-platform-tools to Homebrew/core

### ISSUE THREAD

**Issue by zaoqi** [Homebrew/homebrew-cask#67304]
### Description of feature/enhancement

{{replace this}}

### Justification

{{replace this}}

### Example use case

{{replace this}}

**Comment by zaoqi** [comment]
@vitorgalvao Why? It is a CLI-only open-source tool.

**Comment by vitorgalvao** [comment]
> @vitorgalvao Why? It is a CLI-only open-source tool.

1. Because you didn’t fill the template, thus providing no justification.
2. Because [it is already tracked as such](https://github.com/Homebrew/homebrew-cask/issues/62715).
3. Because some open-source CLI-only casks can’t be in HB (unsure of the case of that one).
4. Because moving an established popular cask after it’s in is harder than having a correct one in the right place from the start *which is the reasoning for closing your PR*.

I’ll respectfully ask you to stop posting for now. At this point you’re just spamming single sentence incomplete replies, and that is unproductive.
