### ISSUE TITLE
/usr/local/lib permission discrepancies

### ISSUE THREAD

**Issue by tb94** [Homebrew/homebrew-cask#68730]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

I'd like to preface that i've looked for an open issue to comment on with further information, but all of the relevant issues were closed. I'm not sure if this is an issue with virtualbox or with homebrew, but i haven't seen this observation anywhere else and wanted to provide it where it can be easily found and potentially used to solve the issue. if it should be moved somewhere else, i would gladly do so.

I've seen more than a few reports of people running into an issue resembling [this post on stack overflow](https://stackoverflow.com/questions/27784545/brew-error-could-not-symlink-path-is-not-writable)
mainly where a directory in /usr/local is owned by root and cannot be written to by homebrew.

This has been plaguing my development environment setup script for days until i realized that this only happens when a set of instructions are performed in a specific order. I noticed that the first thing my script did after installing homebrew was install virtualbox, yet when i installed git instead of virtualbox `brew install git` directly after installing homebrew , these directories are created with the correct permissions.

this is on a fresh installation of Mojave (10.14.6)
with a fresh installation of homebrew (2.1.11)

#### Command that failed
Starting after macOS finishes installing Mojave:
```
$ ls -al /usr/local
total 0
drwxr-xr-x  3 root wheel  96 Sep 6 10:16 .
drwxr-xr-x@ 9 root wheel 288 Sep 6 10:16 ..
-rw-r--r--  1 root wheel   0 Sep 6 10:16 .com.apple.installer.keep

$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
...
$ ls -al /usr/local/lib
total 0
drwxrwxr-x   2 developer admin  64 Sep 6 10:21 .
drwxr-xr-x  15 root      wheel 480 Sep 6 10:21 ..
```
this is where things get interesting.
```
$ brew cask install virtualbox
...
$ ls -al /usr/local/lib
drwxrwxr-x   9 developer admin    288 Sep  6 10:22 .
drwxr-xr-x  15 root      wheel    480 Sep  6 10:22 ..
-rwxr-xr-x   1 root      wheel 973488 May  3 16:12 libosxfuse.2.dylib
lrwxr-xr-x   1 root      wheel     18 Sep  6 10:22 libosxfuse.dylib -> libosxfuse.2.dylib
-rwxr-xr-x   1 root      wheel    933 May  3 16:12 libosxfuse.la
lrwxr-xr-x   1 root      wheel     18 Sep  6 10:22 libosxfuse_i64.2.dylib -> libosxfuse.2.dylib
lrwxr-xr-x   1 root      wheel     16 Sep  6 10:22 libosxfuse_i64.dylib -> libosxfuse.dylib
lrwxr-xr-x   1 root      wheel     13 Sep  6 10:22 libosxfuse_i64.la -> libosxfuse.la
drwxr-xr-x   4 root      wheel    128 Sep  6 11:40 pkgconfig
```
at this point, trying to install anything else with homebrew fails, prompting that `/usr/local/lib/pkgconfig` can't be written to and that you should `sudo chown -R $(whoami) /usr/local/lib/pkgconfig` or something similar. If I repeat the process by wiping the drive, reinstalling mojave, and reinstalling homebrew, we see that installing git instead of virtualbox creates the directory with the proper credentials
```
$ brew install git
...
$ ls -al /usr/local/lib
drwxrwxr-x  15 developer  admin   480 Sep  6 14:16 .
drwxr-xr-x  15 root       wheel   480 Sep  6 14:10 ..
lrwxr-xr-x   1 developer  admin    45 Sep  6 14:16 libpcre2-16.0.dylib -> ../Cellar/pcre2/10.33/lib/libpcre2-16.0.dylib
lrwxr-xr-x   1 developer  admin    39 Sep  6 14:16 libpcre2-16.a -> ../Cellar/pcre2/10.33/lib/libpcre2-16.a
lrwxr-xr-x   1 developer  admin    43 Sep  6 14:16 libpcre2-16.dylib -> ../Cellar/pcre2/10.33/lib/libpcre2-16.dylib
lrwxr-xr-x   1 developer  admin    45 Sep  6 14:16 libpcre2-32.0.dylib -> ../Cellar/pcre2/10.33/lib/libpcre2-32.0.dylib
lrwxr-xr-x   1 developer  admin    39 Sep  6 14:16 libpcre2-32.a -> ../Cellar/pcre2/10.33/lib/libpcre2-32.a
lrwxr-xr-x   1 developer  admin    43 Sep  6 14:16 libpcre2-32.dylib -> ../Cellar/pcre2/10.33/lib/libpcre2-32.dylib
lrwxr-xr-x   1 developer  admin    44 Sep  6 14:16 libpcre2-8.0.dylib -> ../Cellar/pcre2/10.33/lib/libpcre2-8.0.dylib
lrwxr-xr-x   1 developer  admin    38 Sep  6 14:16 libpcre2-8.a -> ../Cellar/pcre2/10.33/lib/libpcre2-8.a
lrwxr-xr-x   1 developer  admin    42 Sep  6 14:16 libpcre2-8.dylib -> ../Cellar/pcre2/10.33/lib/libpcre2-8.dylib
lrwxr-xr-x   1 developer  admin    48 Sep  6 14:16 libpcre2-posix.2.dylib -> ../Cellar/pcre2/10.33/lib/libpcre2-posix.2.dylib
lrwxr-xr-x   1 developer  admin    42 Sep  6 14:16 libpcre2-posix.a -> ../Cellar/pcre2/10.33/lib/libpcre2-posix.a
lrwxr-xr-x   1 developer  admin    46 Sep  6 14:16 libpcre2-posix.dylib -> ../Cellar/pcre2/10.33/lib/libpcre2-posix.dylib
drwxr-xr-x   6 developer  admin   128 Sep  6 14:16 pkgconfig
```

Again, i'm not sure what the core issue is here, but i wanted to bring light to the fact that there's a discrepancy in the way that these directories are being created, and it's caused _a lot_ of people to ask the same question. additionally, people are arguing that `sudo chown -R $(whoami) /usr/local/...` is not safe because these directories should not be owned by a single user yet that's the only way for me to install other packages.

**Comment by vitorgalvao** [comment]
> i've looked for an open issue to comment on with further information, but all of the relevant issues were closed.

A *locked* issue will prevent you from posting, but a *closed* issue will not.

It may help if you reference the issues you found relevant.

The only thing we do to install Virtualbox is tell macOS to install their provided `pkg`, meaning that this is likely caused by their postinstall scripts. What happens to the permissions if you install Virtualbox manually instead of through HBC?

**Comment by brlodi** [comment]
I am having what I believe to be the same issue. Let me know if you'd like me to open a new issue, otherwise details below:

**Summary:** If Homebrew has not created `/usr/local/lib/pkgconfig` before installing VirtualBox, the VirtualBox installer creates it with incorrect permissions and breaks Homebrew.

Steps to reproduce on fresh macOS Mojave:
1. Install Homebrew (using typical install script).
2. Install VirtualBox via `brew cask install virtualbox` OR directly downloading and running the GUI installer. It's fine that it fails due to the kext loading warning; the outcome doesn't change even if you accept and run the installer again. 
3. Attempt to install any core Homebrew formula, such as `git`. The following error is produced and the install fails:
    ```
    Error: The following directories are not writable by your user:
    /usr/local/lib/pkgconfig
    
    You should change the ownership of these directories to your user.
      sudo chown -R $(whoami) /usr/local/lib/pkgconfig
  
    And make sure that your user has write permission.
      chmod u+w /usr/local/lib/pkgconfig
    ```
    Cask installations continue to work (AFAIK they don't use `/usr/local/lib/pkgconfig` anyway). `brew doctor` reports the same permissions issue as the `brew install` error.

For comparison, these steps seem to work fine:
1. Install Homebrew.
2. Install at least one standard Homebrew formula, like `git` (I'm not sure if *every* formula triggers the creation of `/usr/local/lib/pkgconfig`).
3. Only then install VirtualBox.
4. Homebrew works as normal, no errors in `brew doctor`.

File/directory permissions look the same as in @tb94's original issue description above. Running the suggested `chown` and `chmod` commands *does* return Homebrew to functionality.

**Comment by brlodi** [comment]
I have not opened a VirtualBox issue as I'm not sure it really qualifies as a bug on their end. The VirtualBox installer does not modify existing directory permissions, so it's not behaving destructively (which would definitely be a bug). It is merely creating a directory if it does not exist, using what seems to me to be very reasonable permissions.

Having `/usr/local/lib` and descendants owned by the user instead of root is (as far as I know) a Homebrew-specific behavior to accommodate the "no sudo required" mission, so I would expect Homebrew to be responsible for ensuring everything in that hierarchy gets created with appropriate permissions. Is there a reason `/usr/local/lib/pkgconfig` is not created until a formula needs it?

**Comment by vitorgalvao** [comment]
@brlodi Fair enough, I agree and take back what I said about it being their bug.

> Is there a reason `/usr/local/lib/pkgconfig` is not created until a formula needs it?

That I do not know, but I’ll ask.
