### ISSUE TITLE
kubenetes-cli not uninstalled properly

### ISSUE THREAD

**Issue by skvijay007** [Homebrew/homebrew-cask#69174]
- [y] are reporting a bug others will be able to reproduce and not asking a question or requesting software. If you're not sure or want to ask a question do so on our Discourse: https://discourse.brew.sh. To get software added or changed in Homebrew please file a [Pull Request](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)
- [ ] have a problem with `brew install` (or `upgrade`, `reinstall`) a single, Homebrew/homebrew-core formula (not cask) on macOS? If it's a general `brew` problem please file this issue at Homebrew/brew: https://github.com/Homebrew/brew/issues/new/choose. If it's a Linux problem please file this issue at https://github.com/Homebrew/linuxbrew-core/issues/new/choose. If it's a `brew cask` problem please file this issue at https://github.com/Homebrew/homebrew-cask/issues/new/choose. If it's a tap (e.g. Homebrew/homebrew-php) problem please file this issue at the tap.
- [y] ran `brew update` and can still reproduce the problem?
- [y] ran `brew doctor`, fixed all issues and can still reproduce the problem?
- [y] ran `brew gist-logs <formula>` (where `<formula>` is the name of the formula that failed) and included the output link?
- [y] if `brew gist-logs` didn't work: ran `brew config` and `brew doctor` and included their output with your issue?

To help us debug your issue please explain:

- What you were trying to do (and why)
  I was writing script file to install all the necessary tools include minikube. 
- What happened (include command output)
 When installed minikube it installed kubectl/kubernetest-cli in both paths '/usr/local/bin' and '/usr/local/Cellar'. After wards when tried to uninstall minikube using 'brew cask uninstall minikube', it just uninstalled minikube but not kubectl or kubernetest-cli.  So tried to do 'brew uninstall kubernetes-cli', it removed from /usr/local/Cellar but not from /usr/local/bin
- What you expected to happen
When uninstalled minikube, it should have removed kubernetes-cli from both paths "usr/loca/bin and usr/local/Cellar". When uninstalled kubernetes-cli using "brew uninstall kubernetes-cli" it should remove kubectl from '/usr/local/bin' and kubernetes-cli from '/usr/local/Cellar'
- Step-by-step reproduction instructions (by running `brew install` commands)

brew cask install minikube
ls /usr/local/bin - # You will find minikube and kubectl
ls /usr/local/Cellar - # You will find minikube and kubernetes-cli

brew cask uninstall minikube
ls /usr/local/bin - #You will not find minikube but kubectl is still there
ls /usr/local/Cellar - #You will not find minikube but kubernetes-cli is still there

brew uninstall kubernetes-cli
ls /usr/local/bin - #You will still find kubectl
ls /usr/local/Cellar - #You will not find kubernetes-cli

**Comment by vitorgalvao** [comment]
@fxcoudert The [`minikube` cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/minikube.rb) only [links a binary](https://github.com/Homebrew/homebrew-cask/blob/f6c40416e50f7b07d0e51bac5e111705806cc812/Casks/minikube.rb#L14) and [installs the formula](https://github.com/Homebrew/homebrew-cask/blob/f6c40416e50f7b07d0e51bac5e111705806cc812/Casks/minikube.rb#L11).

Seeing as the problem is a leftover binary that the cask did not install directly, this is either `minikube` (the software, not the cask) installing something extra (as @SMillerDev suggested) or something in the formula (which, since you’ve moved the issue, is unlikely). The binary in question (`kubectl`) [is referenced in the formula](https://github.com/Homebrew/homebrew-core/blob/615aeec639c7e7e8f45ef1440ac13a9dca6adbbb/Formula/kubernetes-cli.rb#L29) but not the cask.

Either way, it is not a Homebrew Cask related issue.

**Comment by fxcoudert** [comment]
OK, then I don't understand what the issue is. I definitely cannot reproduce it: after `brew uninstall kubernetes-cli` on my system, `kubectl` is gone.
