### ISSUE TITLE
Is homebrew cask the best way to install Chrome after #Varsectomy?

### ISSUE THREAD

**Issue by afonari** [Homebrew/homebrew-cask#69898]
After Chrome #Varsectomy: https://mrmacintosh.com/google-chrome-keystone-is-modifying-var-symlink-on-non-sip-macs-causing-boot-issues/

In the HN topic someone suggested to do:
```
rm -rf ~/Library/Google/GoogleSoftwareUpdate
rm -rf /Library/Google/GoogleSoftwareUpdate
touch ~/Library/Google/GoogleSoftwareUpdate
touch /Library/Google/GoogleSoftwareUpdate
chmod 000 ~/Library/Google/GoogleSoftwareUpdate
chmod 000 /Library/Google/GoogleSoftwareUpdate
```

After this is done, I installed chrome using cask. I see that In Chrome -> About there is: Update failed (error: 10).

Are there any known downsides of this approach?

**Comment by vitorgalvao** [comment]
> Are there any known downsides of this approach?

To `brew cask upgrade` Google Chrome with Homebrew Cask, you’ll need to use `--greedy` as well, else it will be ignored (because it’s auto-updating software).

Also, you might not get updates as soon as you expect. It depends on when they’re submitted to us and merged.

Finally, that bug only occurred on machines with SIP disabled, *which we don’t recommend*. We don’t even recommend you disable Gatekeeper, and we take advantage of it as a security feature.

In sum, you’re free to use that method and make any changes you desire on your machine, but you do so at your own risk and we won’t offer support for it.

**Comment by afonari** [comment]
Thanks for the explanations and the greedy flag.
