### ISSUE TITLE
How to report cask?

### ISSUE THREAD

**Issue by orihomie** [Homebrew/homebrew-cask#69966]
Hi, my question is about how does cask review goes on here (if there is cask review)?
Found this cask: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/sublime.rb

For me it seems like something hiding itself for sublime text editor, no functionality and (of course) donate button.

**Comment by vitorgalvao** [comment]
> my question is about how does cask review goes on here (if there is cask review)?

Yes, there is. It doesn’t take a hard search to find it, [even for such an old cask](https://github.com/Homebrew/homebrew-cask/pull/15865). There are tons of issues and PRs as examples, as well as extensive documentation.

> For me it seems like something hiding itself for sublime text editor, no functionality and (of course) donate button.

There’s huge text saying “Drag & Drop Media”. Have you tried doing so? Sublime Text doesn’t have a monopoly on the word “sublime”; it’s a dictionary word. It makes a whole lot of sense for this app to be named **sub**lime because it’s a **sub**title downloader. Puns are common in such apps, another example being [**sub**marine](https://www.bitfield.se/submarine/index.html).

Thank you for the concerned report, but this was simple to investigate, especially since you had it open. It’s even a signed app (which, granted, doesn’t preclude it from being malicious).
