### ISSUE TITLE
mpv bad config file name and require setting of hwdec 

### ISSUE THREAD

**Issue by Justsoos** [Homebrew/homebrew-cask#70960]
1, `~/.config/mpv/config` is not the mpv default file name, it has to be `mpv.conf`
2, `hwdec=yes` is default required for MacOS in this mpv.conf file, the cpu usage costs up to  3-4 times if no this settings, and most users of homebrew do not know that 

and BTW, where to pull requests directly? :p

**Comment by vitorgalvao** [comment]
> `~/.config/mpv/config` is not the mpv default file name, it has to be `mpv.conf`

Nowhere in the cask is `~/.config/mpv/config` referenced. `~/.config/mpv` is, which is the correct directory.

> `hwdec=yes` is default required for MacOS in this mpv.conf file

Please provide sources for statements, otherwise we as maintainers can’t make informed decisions. There’s a reason that setting is not enabled by default, [explained in their documentation](https://mpv.io/manual/stable/) under `Quality reduction with hardware decoding`. Not all Macs are capable of hardware decoding (I’d wager the majority in use) and we’re not going to start imposing setting on users, they “[are expected to have reasonable knowledge about the apps they’re installing through us before doing so](https://github.com/homebrew/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md)”. This is an issue to be solved on mpv’s side, not HBCs. If having that setting activated on macOS were imperative, they’d could have introduced a conditional in the code. If they haven’t, why?

> and BTW, where to pull requests directly? :p

See [CONTRIBUTING.md](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md).

Thank you for the tip anyway, but it doesn’t fit on our side.

**Comment by Justsoos** [comment]
In the smallest category, I don't think the original authors of mpv.io were very responsible. 
MacOS has such a user base that is very sensitive to fan hum hum hum by CPU overload, and, as I've quoted, `hwdec=no` the soft decompression is installed by default, even if `hwdec=yes` was set, it will not cause any hardware conflict, and soft decompression will definitely cause Apple's CPU overload.

Homebrew is a "friendly" organization that is kindly prompted to do something lovely after installation, such as prompt of adding a link to /usr/local/bin. That's my understanding.

This is a completely harmless and certainly beneficial thing to the users, why not? Just because of bureaucracy?

**Comment by vitorgalvao** [comment]
> Homebrew is a "friendly" organization that is kindly prompted to do something lovely after installation

Homebrew Cask doesn’t claim to do that anywhere.

> such as prompt of adding a link to /usr/local/bin

That’s regular installation procedure.

> Just because of bureaucracy?

You’ve never before interacted with the project — which has been successfully operated for years — and are acting as if you have all the answers.

https://github.com/mpv-player/mpv/issues/7061 has given you the answer. There is indeed, as expected, a good reason for the setting to not be turned on by default. I see no justification for us to do that ourselves and introduce bugs to our users.
