### ISSUE TITLE
Rename Cask

### ISSUE THREAD

**Issue by jhabdas** [Homebrew/homebrew-cask#71503]
As it stands `brew install mongodb` offers up the `mongodb` cask even though it is not official. Please rename `mongodb` cask to `mongodb-app` to avoid developer confusion. Author is OK with this. Ref linked issue.

**Comment by vitorgalvao** [comment]
Thank you for the report.

> Please rename `mongodb` cask to `mongodb-app`

We don’t do the `-app` suffix; it’s confusing (we know because we’ve tried it) and wouldn’t make it clear it’s an unofficial app.

> Author is OK with this.

Authors don’t have direct say in names of casks in official repos. They can influence them through renaming their own apps, but otherwise they follow a strict [token reference](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).

This has been partially addressed in https://github.com/Homebrew/homebrew-core/pull/43770#issuecomment-527255004, but that didn’t address the software not being official. We [have a protocol for this situation](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md#potentially-misleading-name). Fixing in https://github.com/Homebrew/homebrew-cask/pull/71506.

**Comment by vitorgalvao** [comment]
Small note: please include the cask name in the title, next time.

**Comment by jhabdas** [comment]
Thanks. For contunity https://discourse.brew.sh/t/mongodb-sspl-license/4058/14?u=jos
