### ISSUE TITLE
Convention on adding warnings/notes for the user

### ISSUE THREAD

**Issue by rramphal** [Homebrew/homebrew-cask#73378]
When installing, Unity (https://github.com/Homebrew/homebrew-cask/blob/master/Casks/unity.rb), the `.pkg` fails without explanation if you try to install it without enough available disk space. Is there a convention to let the user know that inadequate disk space might be something they should rule out if installation fails? I'm also thinking that it might reduce false-positive bug issues.

**Comment by vitorgalvao** [comment]
> Is there a convention to let the user know that inadequate disk space might be something they should rule out if installation fails?

No, but that’s not a widespread issue, and it’s true for every piece of software. If you open a bug report it asks for specific info, including running the problematic command (`install`) with debugging flags. I’m guessing (haven’t tested) that would show the problem. If it doesn’t, it wouldn’t be simple for us to do it either, since we’re relying on macOS tools to perform the installation.
