### ISSUE TITLE
Brave Browser Version Scheme

### ISSUE THREAD

**Issue by ModdedGamers** [Homebrew/homebrew-cask#73634]
I think we need to decide on a versioning scheme for the Brave Browser. There are 3 options (that I know of)

1. The one we've been using for a while now.
This is the one I think we should use, as this is the one that the browser uses. An example is 1.4.1, the latest nightly release.
2. The new one that was just introduced by @404NetworkError . This uses 2 different versions, the version number that I prefer, and a version that inserts a 0 instead of a dot between the first and second numbers of the version, i.e. 103.56 instead of 1.3.56. The full version number for this scheme is 79.1.3.56,103.56.
3. Just use the second part of option number 2, the 103.56 part, the version after the comma.

I prefer the first one, as it is the one used in both the browser and in the release notes. I'm interested to hear your opinions.

**Comment by vitorgalvao** [comment]
I don’t care about exact version numbers (and neither do most users, I’d wager) as long as updates happen.

@core-code and @suschizu do care about version numbers and they submit a significant portion of updates (for every cask) which are driven by automated systems that require maintenance, so I’m partial to whatever they prefer to make that easier.

Seeing as the current scheme was introduced by @suschizu in https://github.com/Homebrew/homebrew-cask/pull/72832 and already brought to the `-dev` and `-beta` versions in [homebrew/cask-versions](https://github.com/Homebrew/homebrew-cask-versions) by @404NetworkError, I’d say keeping everything as is now makes more sense.

**Comment by ModdedGamers** [comment]
Alright. I just think it seems a bit complicated

**Comment by core-code** [comment]
thanks for your discussion. we are certainly interested in having the actual version number in there. but as long as this requirement is met, we are happy with anything, as long as it contains either the CFBundleVersion or CFBundleShortVersionString and as long as the ML system of @ran-dall is able to help us submit the updates. 

the current system is 
'CFBundleShortVersionString,CFBundleVersion'
which is currently 
'78.1.0.1,100.1'

if you want to simplify things by having just one of those two in there (so either just '78.1.0.1' or just '100.1') we are fully ok with that. thanks!

**Comment by suschizu** [comment]
thanks @vitorgalvao

> The one we've been using for a while now.
This is the one I think we should use, as this is the one that the browser uses. An example is 1.4.1, the latest nightly release.

@ModdedGamers I've changed the version notation because I've updated the brave browsers appcast to the feed that is used by the app itself as SUFeedURL. The feed is well supported and reliable and uses the bundle version in the download link - I think it would be much more complicated to transform 1.0.1 into 100.1 instead of just using the bundle version here. 
I added the short version string because it is used by the app - this notation wouldn't be necessary - but this is the apps version that is shown in the finder

![image](https://user-images.githubusercontent.com/16004333/70151110-69e42700-16ab-11ea-810b-b70b97ba7481.png)
