### ISSUE TITLE
Analytics purge (How to determine it without Analytics ?)

### ISSUE THREAD

**Issue by Rbcafe** [Homebrew/homebrew-cask#74043]
### Description of feature/enhancement

Greetings,

We observe that there is some "cask purge commits" related to Analytics :

https://github.com/Homebrew/homebrew-cask/commit/cc482d5ffa292da05f714b4ad513e83832c3be38
https://github.com/Homebrew/homebrew-cask/commit/3d28779db4cd7777b18cc87d5c660712c49b97cc
https://github.com/Homebrew/homebrew-cask/commit/25a1054b3866288987ef17d10377de56054aee48
https://github.com/Homebrew/homebrew-cask/commit/cca77b9bf113a7278b85fa7ccd09902bef31737e

Should HomebrewCask add an option inside casks to avoid "Analytics purge" ?

### Question 

Can we consider that the people who download software from the "Analytics purge" list does not use Analytics ?

### Justification

I disabled Analytics and use a specific software or download a specific software on a regular basis. How can you accurately determine that there is an use for the software if there is no Analytics linked to it ?

Best regards.

@Rbcafe

**Comment by vitorgalvao** [comment]
> Should HomebrewCask add an option inside casks to avoid "Analytics purge" ?

We do the purge on purpose, adding an option inside a cask to exclude it wouldn’t make sense.

> Can we consider that the people who download software from the "Analytics purge" list does not use Analytics ?

Yes, but we also consider that the people who work on HBC are volunteers that have to focus their attention where it makes the most difference.

> I disabled Analytics and (…) download a specific software on a regular basis.

That would still only count as one user.

> How can you accurately determine that there is an use for the software if there is no Analytics linked to it ?

All software that is removed uses more than one source to determine usage, and it has to be below the threshold in *all* of them. If you had analytics enabled, perhaps it would have been above the thresold on HBC.

You’re free and welcome to not share any analytics data, but that also means we can’t cater to your needs because we don’t know they exist. It’s a tradeoff; you can decide what you prefer.

You’re also welcome to resubmit the removed cask. The system contemplates that.
