### ISSUE TITLE
Failure while executing; `/usr/bin/sudo -E -- /usr/sbin/dseditgroup -o delete access_bpf` exited with 64. Here's the output: Group not found

### ISSUE THREAD

**Issue by dione2017** [Homebrew/homebrew-cask#74479]
brew cask reinstall --force  wireshark
==> Downloading https://1.na.dl.wireshark.org/osx/all-versions/Wireshark%203.2.0%20Intel%2064.dmg
Already downloaded: /Users/lijialin/Library/Caches/Homebrew/downloads/d0e402a9e8202174b53fa3f39b8d56637021df493cea55974a1cef025290e011--Wireshark 3.2.0 Intel 64.dmg
==> Verifying SHA-256 checksum for Cask 'wireshark'.
==> Uninstalling Cask wireshark
Group not found.
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/sbin/dseditgroup -o delete access_bpf` exited with 64. Here's the output:
Group not found.

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/dsl/base.rb:16:in `system_command'
/usr/local/Caskroom/wireshark/.metadata/3.0.7/20191218035135.374/Casks/wireshark.rb:19:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:41:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:41:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_flight_block.rb:28:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:454:in `block in uninstall_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:450:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:399:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:138:in `uninstall_existing_cask'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:91:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:127:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:13:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:7:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/reinstall.rb:7:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:158:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:123:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:102:in `<main>'

`brew cask install/reinstall/uninstall wireshark ` get the same result, but others plugin works right. my computer is macobook pro 2019 with osx 10.15.2

**Comment by Tenzer** [comment]
I don't know if this is related, but after I got Wireshark upgraded from version 3.1.0 to 3.2.0 just now, I got a "Wireshark: Permission denied" error message every time I open a new terminal in iTerm.

I narrowed it down to be triggered by `/usr/libexec/path_helper` when it is executed from `/etc/profile` and was caused by my user not having permissions to read `/etc/paths.d/Wireshark`:
```
[jeppe@reventon ~]$ ls -l /etc/paths.d/
total 8
-rw-------  1 root  wheel  43 20 Nov 23:19 Wireshark
```

As I don't need to invoke Wireshark from the terminal I opted to just delete the file, but changing the permissions to 644 would probably fix it as well.

**Comment by jabenninghoff** [comment]
@Tenzer thanks for sharing, I had the same problem! I can confirm that changing permissions fixes the issue - `sudo chmod 644 /etc/paths.d/Wireshark`

**Comment by vitorgalvao** [comment]
Fixing in https://github.com/Homebrew/homebrew-cask/pull/74502.

@dione2017 Next time, please do fill the template (as it asks you to). Your issue is severely incomplete and hard to read, and had a solution not have been provided by @Tenzer and @jabenninghoff, I would have closed the issue without review (again, as the template warns).
