### ISSUE TITLE
Cannot install google-cloud-sdk #75097

### ISSUE THREAD

**Issue by thouis** [Homebrew/homebrew-cask#80163]
See #75097 for essential details.  This is not an upstream issue, as claimed by @vitorgalvao in that issue.

Old version of python2.7 on Catalina is causing google-cloud-sdk to fail.  

Fix is to reinstall python@2 using homebrew, as explored in https://github.com/wting/autojump/issues/540.

At the very least, #75097 should be updated with instructions to fix.

**Comment by vitorgalvao** [comment]
> Old version of python2.7 on Catalina is causing google-cloud-sdk to fail.

Which is an upstream issue. We neither control which version of Python comes with macOS versions, nor the Google Cloud SDK.

> Fix is to reinstall python@2 using homebrew, as explored in wting/autojump#540.

Homebrew doesn’t carry python 2, because it’s EOL.

> At the very least, #75097 should be updated with instructions to fix.

Your suggested fix won’t work (see above) and doing so would only solve the issue for Homebrew Cask users. What’s failing is their script. This needs to be fixed upstream *for everyone*.

Don’t ignore the templates. Repeated offences may result in banning.

**Comment by thouis** [comment]
Sorry.  But works for me, and it was the homebrew python that was failing at first, and for which reinstalling fixed it.

**Comment by vitorgalvao** [comment]
Again, Homebrew no longer carries `python@2`, so you can’t reinstall it. And according to that thread, uninstalling does also work, *which is what you should do anyway*.

If the issue was a formula that no longer exists and will not be reinstated, problem solved.

**Comment by thouis** [comment]
Great.  Perhaps that explanation should be added to #75097.

**Comment by vitorgalvao** [comment]
> Great.  Perhaps that explanation should be added to #75097.

It shouldn’t, no. [`caveats` are to be used sparingly](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md#caveats) and there have been two complaints on this, a cask that is installed *five thousand* times a month.

Just because you bumped into the issue doesn’t make it widespread. There’s nothing else to discuss here. I kindly request that you at least take a cursory look at our documentation before making new issues. You’ve ignored the template and information that is readily available, which could have saved us both a lot of time.

**Comment by vitorgalvao** [comment]
> Great.  Perhaps that explanation should be added to #75097.

It shouldn’t, no. [`caveats` are to be used sparingly](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md#caveats) and there have been two complaints on this, a cask that is installed *five thousand* times a month.

Just because you bumped into the issue doesn’t make it widespread. There’s nothing else to discuss here. I kindly request that you at least take a cursory look at our documentation before making new issues. You’ve ignored the template and information that is readily available, which could have saved us both a lot of time.
