### ISSUE TITLE
Proposal to integrate sparkle-cli to upgrade casks using Sparkle.framework

### ISSUE THREAD

**Issue by MTCoster** [Homebrew/homebrew-cask#80710]
### Description of feature/enhancement

I noticed recently that part of the Sparkle 2.0 branch is a new command line utility (`sparkle-cli`) which can be used to trigger an update for any app using `Sparkle.framework`.

Homebrew Cask currently does not touch any app with an `auto_updates true` stanza when running `brew cask upgrade`; this integration would allow it to be effective for many more apps.

I am willing to undertake the development required for this feature, but I may need some guidance as my ruby is a little rusty (been working with rust too long :p).

Since Sparkle 2.0 is still considered unstable, I suggest waiting until its official release before undertaking any of this.

**Steps required:**

 - [ ] Wait for Sparkle 2.0 to stabilize **(blocking)**
 - [ ] Add `sparkle-cli` formula to `homebrew-core`
 - [ ] Add a `'sparkle'` value to the `auto_updates` stanza to indicate a Sparkle-updated app (can this be automated in any way?)
 - [ ] Execute `sparkle` with the `.app` path as a parameter, with none of the interactivity flags, and check for successful completion.

### Justification

This enhancement would push Homebrew Cask closed towards its goal(?) of a complete app management system for macOS.

### Example use case

```
➜ brew cask upgrade alt-tab  # or any Sparkle-updated app
```

or even

```
➜ brew cask upgrade  # to update every app
```

**Comment by vitorgalvao** [comment]
It is common for apps using the Sparkle framework to not keep their feeds up to date, or be late in updating them. Is it possible this could make an app downgrade instead of upgrade, or is `sparkle-cli` smart enough to realise the current version is higher and do nothing?

There’s also the consideration that this will bring whatever version HBC thinks is installed into further disarray, but that’s another matter.

And what’t the use case for `brew cask outdated`? Would `sparkle-cli` run on all of those? That seems like it might make the operation slower. There also needs to be a timeout in case a feed is not reachable.

Pinging @core-code and @suschizu into this discussion due to extensive experience with Sparkle, in case you have something to add.

**Comment by core-code** [comment]
note, we've been using 'sparkle-cli' in very early versions of MacUpdater some years back. 

one problem is where to get the feed address from. using the SUFeedURL from the Info.plist is just a no-go. some apps don't store it there, in other cases this feed will only pick up minor updates. we've dumped that approach years ago.

i don't really get what you are trying to achieve. 'Homebrew Cask' is already a system that is perfectly capable of installing the latest version of *any* cask. 

if the problem is that 'brew cask upgrade' will not update casks that have 'auto_updates' set, why not just introduce a flag so that it will also update those casks? instead of trying to add another wholly separate and error-prone additional way to do something thats already possible in a reliable and supported fashion? maybe i am not getting something here...

**Comment by MTCoster** [comment]
> [...] is sparkle-cli smart enough to realise the current version is higher and do nothing?

From messing about with it a little, I *think* so (don’t hold me to that; I haven’t tested rigorously). If not, that would be a blocking upstream issue.

> And what’t the use case for brew cask outdated? Would sparkle-cli run on all of those?

This is something I hadn’t considered - that does seem wildly inefficient.

> i don't really get what you are trying to achieve. 'Homebrew Cask' is already a system that is perfectly capable of installing the latest version of _any_ cask.

My line of thinking was that Homebrew Cask currently leaves casks with `auto_updates true` alone when running `upgrade`, and that it would be “easier” (/more efficient?) to defer to Sparkle where possible instead of effectively running `uninstall`/`install`. Although thinking about it now, that’s essentially all `upgrade` does already.

**Comment by core-code** [comment]
> and that it would be “easier” (/more efficient?) to defer to Sparkle where possible instead of effectively running uninstall/install

i think it is a thousand times easier to modify cask's 'upgrade' to accept "--dont-skip-auto_update-apps" than to try to add an additional system to update apps.

> that would be a blocking upstream issue.

note that i've filed a few bug-reports about 'sparkle-cli' a while back and that didn't result in any fixes being added. despite the look of it, it is not a one-stop-system to update each and every Sparkle-capable app.

**Comment by MTCoster** [comment]
> despite the look of it, it is not a one-stop-system to update each and every Sparkle-capable app

On that note, I think it’s time to close this issue.

Thank you both for your comments, and for helping me to see why this isn’t as sensible an idea as I first thought.

**Comment by vitorgalvao** [comment]
> one problem is where to get the feed address from

I was assuming it was some sort of smart CLI where you could give it the app bundle as a target and it would figure out the rest. If we need to give it the feed it becomes less useful, although we could leverage our own `appcast` stanza.

> if the problem is that 'brew cask upgrade' will not update casks that have 'auto_updates' set, why not just introduce a flag so that it will also update those casks?

We already have it (`--greedy`).

> Homebrew Cask currently leaves casks with `auto_updates true` alone when running `upgrade`

Not in the case of your top use case. When you specify an app as an argument to `upgrade`, `auto_updates` doesn’t ignore it.

> we've dumped that approach years ago.
> (…)
> note that i've filed a few bug-reports about 'sparkle-cli' a while back and that didn't result in any fixes being added. despite the look of it, it is not a one-stop-system to update each and every Sparkle-capable app.

You have enough experience in this matter that if you’ve tried it and found it to not work, that’s enough for me.

> Thank you both for your comments, and for helping me to see why this isn’t as sensible an idea as I first thought.

Thank you for a well written feature report, the idea, and offering to work on it.

**Comment by core-code** [comment]
> and it would figure out the rest.

it tries to figure out the feed from the Info.plist SUFeedURL. thats not good enough in my opinion though.

> You have enough experience in this matter that if you’ve tried it and found it to not work, that’s enough for me.

thanks there, this is indeed my believe. just for reference, i cannot say if improvements to 'sparkle-cli' have made it far better recently. my last experience has been mid 2018 when we abandoned trying to use it. i doubt there have been fundamental changes though,
