### ISSUE TITLE
Install an specific version of a package

### ISSUE THREAD

**Issue by albertocubero** [Homebrew/homebrew-cask#81080]
### Description of feature

Is there any way by command line to install a specific version of a package? I have investigated a lot and the ways I found are very tricky, like this ([this](https://www.jverdeyen.be/mac/downgrade-brew-cask-application/)).

### Justification

Im coding a React Native App at v0.59. To use [react-native-debugger](https://github.com/jhen0409/react-native-debugger) I need an old version (v0.9.14) but when I install it by brew, its installed the lastest (in this moment, v0.11.0-beta-0). 

### Example use case

brew cask install react-native-debugger@0.9.14

**Comment by vitorgalvao** [comment]
> brew cask install react-native-debugger@0.9.14

That would require a new cask, which is what [homebrew/cask-versions](https://github.com/Homebrew/homebrew-cask-versions) is for. Though we’re unlikely to accept that version because that’s not a dump for every version every user needs.

Consider hosting your own [tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md).
