### ISSUE TITLE
For updating a cask - document using github personal access token along with required permission

### ISSUE THREAD

**Issue by mohanraj-r** [Homebrew/homebrew-cask#84460]
### Description of feature/enhancement

I recently went through the process of [updating a cask](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask). 
It was a fairly straightforward and automated process! Kudos 👍 
My only issue was the requirement to give the github password - even though it says it is never stored.
I am never comfortable with giving out passwords - even to automated open-source tools.
I managed to create a personal access token with restricted permissions (taking a guess on what the tool would need and it worked! The PR was successfully created. 
It would be great to document the alternative of using a Github personal access token along with the exact permissions needed for the token.

### Justification
Would be better in terms of restricted scope, improved security  and trust from user.

**Comment by vitorgalvao** [comment]
That is a requirement of `hub`, a dependency of `cask-repair`. Both tools are open source and you’re free to inspect their code.

You’re also free to update the cask manually.

As the sole developer of `cask-repair`, I’ve been wanting to move off `hub` (for other reasons) and using the API directly for a while. When / if I ever do, I may consider this, but right now I doubt it. I’ll not document an alternative approach because:

1. It has been like this for years, it’s used by tons of people, and you’re the first one to ever mention it.
2. `hub` is already a pain to deal with; most bug reports I get are due to it, and I’m in no way eager to get more.

**Comment by mohanraj-r** [comment]
Thanks for creating and maintaining this tool. 
Its not that I don't trust the tool - its just best practice in terms of Principle of least privilege and any bugs accidentally causing havoc etc. Anyways I get you are resource constrained. I will leave it at that.

**Comment by vitorgalvao** [comment]
> its just best practice in terms of Principle of least privilege

I’m not disagreeing. But like I said, that’s a requirement of another tool, not `cask-repair` directly. And seeing as you’re the first to ever bring that up, you can imagine how that’s really low on the list of priorities.

> and any bugs accidentally causing havoc etc.

And for the time being, those would have to be reported to `hub`, the tool `cask-repair` depends on that I don’t maintain, and that is created by the same person that’s now developing the official github CLI tool.

You’re complaining in the wrong place.
