### ISSUE TITLE
Cannot install adobe-creative-cloud (erro code 72)

### ISSUE THREAD

**Issue by misakisuna705** [Homebrew/homebrew-cask#85080]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [ ] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

When I try to install creative cloud, the installer return erro code 72.

#### Command that failed

```
brew cask install adobe-creative-cloud
```

#### Output of command with `--force --verbose --debug`

```
==> Downloading https://ccmdls.adobe.com/AdobeProducts/KCCC/1/osx10/CreativeCloudInstaller.dmg
Already downloaded: /Users/misakisuna/Library/Caches/Homebrew/downloads/999ed46ed9a0fc491d156ffac99b05d559dce85d0486ebaaa663aa0e2232cec9--CreativeCloudInstaller.dmg
==> No SHA-256 checksum defined for Cask 'adobe-creative-cloud', skipping verification.
==> Installing Cask adobe-creative-cloud
hdiutil attach -plist -nobrowse -readonly -noidme -mountrandom /var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/d20200627-11810-ddg5fv /Users/misakisuna/Library/Caches/Homebrew/downloads/999ed46ed9a0fc491d156ffac99b05d559dce85d0486ebaaa663aa0e2232cec9--CreativeCloudInstaller.dmg
mkbom -s -i /var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/20200627-11810-unjdmf.list -- /var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/20200627-11810-1gvopfr.bom
ditto --bom /var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/20200627-11810-1gvopfr.bom -- /private/var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/d20200627-11810-ddg5fv/dmg.wBqwTy /var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/d20200627-11810-gag85p
diskutil eject /private/var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/d20200627-11810-ddg5fv/dmg.wBqwTy
cp -pR /var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/d20200627-11810-gag85p/Creative\ Cloud\ Installer.app/. /usr/local/Caskroom/adobe-creative-cloud/latest/Creative\ Cloud\ Installer.app
chmod -Rf +w /var/folders/tt/vgkgdl9s6d5bp_lgvk69xhp00000gn/T/d20200627-11810-gag85p
==> Running installer script '/usr/local/Caskroom/adobe-creative-cloud/latest/Creative Cloud Installer.app/Contents/MacOS/Install'
Progress of PDM is 0
Progress of PDM is 100
Progress of PDM is 0
Progress of PDM is 5
Progress of PDM is 10
Progress of PDM is 66
Progress of PDM is 80
Progress of PDM is 100
==> Purging files for version latest of Cask adobe-creative-cloud
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env PATH=/usr/local/bin:/usr/local/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin /usr/local/Caskroom/adobe-creative-cloud/latest/Creative\ Cloud\ Installer.app/Contents/MacOS/Install --mode=silent` exited with 72. Here's the output:
Starting Installer...
Progress of PDM is 0
Progress of PDM is 100
Progress of PDM is 0
Progress of PDM is 5
Progress of PDM is 10
Progress of PDM is 66
Progress of PDM is 80
Progress of PDM is 100
Some error occured during installation. Instalaltion Cannot continue
Installer returning with erro code 72

Follow the instructions here:
  https://github.com/Homebrew/homebrew-cask#reporting-bugs
/usr/local/Homebrew/Library/Homebrew/system_command.rb:176:in `assert_success!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:53:in `run!'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:29:in `run'
/usr/local/Homebrew/Library/Homebrew/system_command.rb:33:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/installer.rb:32:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:218:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/set.rb:777:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:209:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:101:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:22:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/install.rb:16:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/abstract_command.rb:36:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:150:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/cmd.rb:92:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:9:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew Version
2.4.2
==> macOS
10.15.5
==> SIP
Enabled
==> Java
14.0.1
==> xattr issues
<NONE>
==> Gatekeeper support
Enabled
==> Homebrew Cask Install Location
<NONE>
==> Homebrew Cask Staging Location
/usr/local/Caskroom
==> Homebrew Cask Taps:
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask (3598 casks)
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-fonts (1547 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/ruby-macho-2.2.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-rspec-1.40.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rubocop-performance-1.6.1/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/rexml-3.2.4/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/plist-3.5.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/mechanize-2.7.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/activesupport-6.0.3.2/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/zeitwerk-2.3.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/tzinfo-1.2.7/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/thread_safe-0.3.6/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/i18n-1.8.3/lib
/usr/local/Homebrew/Library/Homebrew/vendor/bundle/bundler/../ruby/2.6.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/universal-darwin19
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin19
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19
/usr/local/Homebrew/Library/Homebrew
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/local/Homebrew/Library/Homebrew/shims/scm:/usr/bin:/bin:/usr/sbin:/sbin"
SHELL="/bin/zsh"
```

#### Output of `brew tap`

```
homebrew/bundle
homebrew/cask
homebrew/cask-fonts
homebrew/core
mattisg/mattisg
universal-ctags/universal-ctags
```

**Comment by vitorgalvao** [comment]
I can reproduce on a clean VM. I was also able to install by running their command outside of HBC.

But we’ll need a PR for this. Adobe is incredibly user-hostile—abusively so—and we’ve wasted far too much time on their draconian installation procedures. Bending to their will is an awful way to spend one’s free time.

Will leave this open for interested parties. If you have the same issue, please do not post “I have this too” (that’s what “Pick your reaction” is for). Only make a comment if you have something useful to add, be it more information on the error or ideas on how to solve it.

**Comment by ran-dall** [comment]
@vitorgalvao I've actually been trying to fix this for the last few days since I noticed it. I believe the problem is how Adobe handles their sign-in now. If I'm not mistaken, they are requiring 2FA on accounts and require you to sign in / verify before the installation proceeds. 

(Unfortunately, my wife is Adobe user (as a graphic designer) so we have an account, and I don't remember turning 2FA on. I personally try to avoid Adobe like the plague because 'user-hostile' doesn't even begin to describe all the bloat and heartache (for your OS, of course) Adobe comes with)

Also, `--silent` also makes no difference anymore. I'm pretty sure the 2FA based sign-in changed the entire installation process.

That said, wouldn't all this qualify this as a 'walled' build?

**Comment by ran-dall** [comment]
ping @danielbayley Perhaps you have some insight as I believe you push the current installation scheme we have for `adobe-creative-cloud`?

**Comment by vitorgalvao** [comment]
> wouldn't all this qualify this as a 'walled' build?

To be considered a [walled build](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask), two things are needed:

1. `url` and `homepage` are on different hosts.
2. Going to the page and trying to download manually is impossible without giving some information.

The second point is valid even if giving a fake email would work, because not everyone will think of that. Cask downloads are the easiest part to compromise without our knowledge, as they pull from servers we have no control over. We want downloads to be auditable by people who don’t know how to code, because that gives us more eyes. It’s simple to understand what `homepage` and `url` do, and that if a piece of software is being downloaded from a different host from its page, it may not be a legitimate download.

The definition of walled build exists [for **security**](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#unofficial-vendorless-and-walled-builds):

> We do not accept these casks since they offer a higher-than-normal security risk.

It’s a way of us saying “verifying this isn’t malware would require a level of vigilance we cannot promise”, so we refuse it. Those cases are (relatively) rare, and teams who want to have their software as a cask are often willing to fix one of the walled build points.

Even if this cask fulfils point **2**, it’s safe because of point **1**. _Both_ are required.

Which doesn’t prevent us from rejecting a cask because the accumulation of one of those points together with something unrelated makes us not want to support it. It just isn’t called a walled build.

---

> I believe the problem is how Adobe handles their sign-in now. If I'm not mistaken, they are requiring 2FA on accounts and require you to sign in / verify before the installation proceeds.

I can confirm I was able to install this cask on a clean VM by `brew cask fetch`ing and running the `installer script:` command on a terminal, so this may be fixable.

> my wife is Adobe user (as a graphic designer)

Adobe is a major reason why I’ve became less interested in graphic design. Affinity Designer is driving the stake even further, due to all the bugs. People swear by it, but if you need your work *precise*—[which I do](https://cottonbureau.imgix.net/products/originals/37227_5j99.png)—it’s a nightmare.

**Comment by ran-dall** [comment]
@vitorgalvao Found the problem.

`PIM Validation Failed:Process certificate didnt match to Adobe certificate! CANameChain: Developer ID Application: Adobe Inc. (JQ525L2MZD){|}Developer ID Certification Authority{|}Apple Root CA`

I don't think this is fixable from within HBC.

**Comment by ran-dall** [comment]
@vitorgalvao Ok, I have a fix.

I found this forum post: https://community.adobe.com/t5/download-install/creative-cloud-installation-fails-at-3-pim-validation-failed-process-certificate-didnt-match-to/td-p/10540858?page=1

Which suggests using the alternative link here: https://helpx.adobe.com/cy_en/download-install/kb/creative-cloud-desktop-app-download.html

---

So I replace the link and made some adjustments...

```ruby
...
  url 'https://ccmdl.adobe.com/AdobeProducts/KCCC/CCD/5_2/osx10/ACCCx5_2_0_436.dmg'
  name 'Adobe Creative Cloud'
  homepage 'https://creative.adobe.com/products/creative-cloud'

  installer script: {
                      executable:   "#{staged_path}/Install.app/Contents/MacOS/Install",
                      args:         ['--mode=silent'],
                      sudo:         true,
                      print_stderr: false,
                    }
...
```

Now, I can it to install, just fine.

```shell
$ brew cask install adobe-creative-cloud
==> Downloading https://ccmdl.adobe.com/AdobeProducts/KCCC/CCD/5_2/osx10/ACCCx5_2_0_436.dmg
==> No SHA-256 checksum defined for Cask 'adobe-creative-cloud', skipping verification.
==> Installing Cask adobe-creative-cloud
==> Running installer script '/usr/local/Caskroom/adobe-creative-cloud/latest/Install.app/Contents/MacOS/Install'
Starting installer...
Installation successful.
🍺  adobe-creative-cloud was successfully installed!
```

---

How should I proceed? 

A thought: I feel like that `url` link should be versioned but I don't know if we can find a proper `appcast` for this...

**Comment by ran-dall** [comment]
#85084

**Comment by danielbayley** [comment]
> a graphic designer) so we have an account, and I don't remember turning 2FA on. I personally try to avoid Adobe like the plague because 'user-hostile' doesn't even begin to describe all the bloat and heartache (for your OS, of course) Adobe comes with)

> ping @danielbayley Perhaps you have some insight as I believe you push the current installation scheme we have for `adobe-creative-cloud`?

**Comment by danielbayley** [comment]
> ping @danielbayley Perhaps you have some insight as I believe you push the current installation scheme we have for `adobe-creative-cloud`?

@ran-dall @vitorgalvao Sorry, been extremely busy! It's was a while ago now, but I remember working on a local copy of this cask, with quite a few changes that didn't quite make it into a PR before life got in the way… basically a long list of additional files and shit this app leaves all over the place! Additionally working on a script to make it easier to find files related to a given app…

I'll take a look at your PR changes though, nice one 👍

> Adobe is incredibly user-hostile—abusively so

> (Unfortunately, my wife is Adobe user (as a graphic designer) so we have an account, and I don't remember turning 2FA on. I personally try to avoid Adobe like the plague because 'user-hostile' doesn't even begin to describe all the bloat and heartache (for your OS, of course) Adobe comes with)

Tell me about it 🤦🏻‍♂️ As someone who wears many hats including motion designer, I am stuck with it because of their monopoly… Unfortunately, nothing compares to After  Effects and Illustrator! I think all the decent engineers work on the apps themselves and they have actual clowns on all the installer stuff… it leaves an absolute mess everywhere! Hate them for it, and the way they run their company 😡
