### ISSUE TITLE
Ao repo is abandoned, switch to new fork

### ISSUE THREAD

**Issue by StoppingBuck** [Homebrew/homebrew-cask#86255]
#### Description of issue

The [Ao Cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/ao.rb) currently sources from https://github.com/klaussinani/ao however that repo seems to have been abandoned (no commits since October 2019, and several serious bugs in current version), so [a fork](https://github.com/pythonInRelay/ao) has been established to take over and fix the bugs - read [this issue](https://github.com/klaussinani/ao/issues/142) for more info.

I suppose this means we should switch the Cask to use the forked repo.

**Comment by vitorgalvao** [comment]
> however that repo seems to have been abandoned

“Seems like” isn’t enough. It’s been less than a year.

> so [a fork](https://github.com/pythonInRelay/ao) has been established to take over and fix the bugs

That’s a random fork with close to no stars and only 13 commits ahead. There’s no guarantee it will continue to be maintained or that the user is trustworthy.

> I suppose this means we should switch the Cask to use the forked repo.

I definitely doesn’t. We don’t switch users to random forks from under their feet. [Forks have specific naming and inclusion rules](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#forks-and-apps-with-conflicting-names) and this one wouldn’t be accepted due to it’s lack of popularity.

The only way we’d switch the cask to that fork would be if the author of the original officially endorsed it.
