### ISSUE TITLE
Stanza: Path

### ISSUE THREAD

**Issue by MGatner** [Homebrew/homebrew-cask#86686]
### Description of feature/enhancement

`brew cask _stanza` is incredibly helpful for programmatic access to Cask statuses and information. The one thing I can't find a way to acquire without heavy parsing is the path to Homebrew's file records.

### Justification

Working with Casks from scripts there is no easy way to determine actual installed files related to the casks: some way of getting back a definitive path to the cask manifest as it is installed on the system.

### Example use case

```
$ brew cask info cyberduck
cyberduck: 7.4.1.33065 (auto_updates)
https://cyberduck.io/
/usr/local/Caskroom/cyberduck/7.4.1.33065 (123B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/cyberduck.rb
==> Name
Cyberduck
==> Artifacts
Cyberduck.app (App)
==> Analytics
install: 1,563 (30 days), 5,888 (90 days), 24,955 (365 days)
```

In the above example I would like `brew cask _stanza path cyberduck` to return **/usr/local/Caskroom/cyberduck/7.4.1.33065**.

**Comment by MGatner** [comment]
FYI currently I'm using this:
```
PATH=`brew cask info cyberduck | awk 'NR==3 { print $1 }'`
```

**Comment by vitorgalvao** [comment]
`_stanza` does what it means, it prints the computed value of [a stanza](https://en.wikipedia.org/wiki/Stanza_(computing)). There’s no `path` stanza, does `_stanza` doesn’t work on it. What you’re asking for isn’t an extension for a feature, but an *exception* to it. As per the documentation, `_stanza` is an internal command, which is why it starts with `_`. It’s there because it’s convenient *and easy to have*, not to be exapanded.

Since we’re joining `brew` and `brew cask` more and the former also provides that `info` detail, making this a `brew cask` command wouldn‘t make sense. If it were a feature both could share, I’d see a stronger case for it.

Try suggesting this to [Homebrew/brew](https://github.com/Homebrew/brew) as a feature that works for both formulae and casks.

**Comment by MGatner** [comment]
Sounds good, thanks for the feedback.

Any reading you can point me to on these plans to for "joining `brew` and `brew cask` more"? I'm curious how this may affect scripts I'm developing on top of each of these frameworks.

**Comment by vitorgalvao** [comment]
It essentially means having less repetition between `brew` and `brew cask` commands, and making the `brew` commands do both. An example is the removal of `brew cask search` in favour of `brew search`.

**Comment by MGatner** [comment]
That sounds awesome. Would this include deeper integrations beyond the CLI? Like incorporating Casks into some of the `Formulary` class methods?

**Comment by vitorgalvao** [comment]
Formulae and casks are built too differently for that to be any consideration as of now.
