### ISSUE TITLE
Metasploit cask pointing to a broken link

### ISSUE THREAD

**Issue by remillan** [Homebrew/homebrew-cask#87009]
I was trying to "brew cask install metasploit", but keep getting a broken link error (error: Download failed on Cask 'metasploit' with message: Download failed: https://osx.metasploit.com/metasploit-framework-5.0.101+20200724102901-1rapid7-1.pkg)

Already tried brew update-reset && brew update

When I check the metasploit cask json file (https://formulae.brew.sh/api/cask/metasploit.json) it is pointing to a build that is no longer available (https://osx.metasploit.com/metasploit-framework-5.0.101+20200724102901-1rapid7-1.pkg)

I would suggest pointing to the latest package available (https://osx.metasploit.com/metasploitframework-latest.pkg), instead of a specific build, since they only keep a week's worth of builds in the repo.

**Comment by ran-dall** [comment]
@remillan Thanks for bringing this to my attention. I'll take your suggestion under advisement, because it might actually save some time from folks opening issues. I'm still a bit reluctant to switch to `:lastest` and `:no_check` but if this keeps happening, we'd be left with no other option. There's also a build that was on Hacker's Brew too that I think was being auto-built. I don't know what happened to it but I'll look into that as well. 

I'll fix this shortly.
