### ISSUE TITLE
Servo Cask Removal

### ISSUE THREAD

**Issue by neeldug** [Homebrew/homebrew-cask#89220]
### Description of feature/enhancement

Servo's cask doesn't really provide any real-world usage as it's still under development.

### Justification

The release being used in Homebrew itself is marked as nightly on the website.

### Example use case

N/A

**Comment by vitorgalvao** [comment]
> The release being used in Homebrew itself is marked as nightly on the website.

[It’s the only one, so that’s not an issue](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

> Servo's cask doesn't really provide any real-world usage as it's still under development.

People are downloading it for *something*.

```
servo
30 days: 24 (#1564)
90 days: 46 (#2016)
365 days: 134 (#2765)
Age: 1536 days (added 2016, July 01)
```

It’s not the most popular cask and could do with improvements (like a `zap`) but it’s not a maintenance burden either and there’s some interest in it, so I don’t see a compelling reason to remove it.
