### ISSUE TITLE
BlueStacks cask is worse than not having a cask for it

### ISSUE THREAD

**Issue by TheKnarf** [Homebrew/homebrew-cask#89713]
The [BlueStacks cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/bluestacks.rb) doesn't install [BlueStacks](https://www.bluestacks.com/). Instead, it downloads the installer for BlueStacks and asks you to manually run it. No other recipes that I know of downloads an installer and let you manually click through the installer, that is kinda not the point of homebrew. It would be better to not have the cask and do everything manually if I first have to.

Since `brew cask install bluestacks` simply downloads the installer, `brew cask uninstall bluestacks` simply removes the installer but still leaves bluestacks installed on my computer.

**Comment by vitorgalvao** [comment]
> No other recipes that I know of downloads an installer and let you manually click through the installer

Search for [`installer manual:`](https://github.com/Homebrew/homebrew-cask/blob/b593c4e3de4c565383487022110ac62c0f4ab556/Casks/bluestacks.rb#L14) and you’ll find more.

> that is kinda not the point of homebrew.

The point is to do the most we can. For these, we can only get this far.

> It would be better to not have the cask and do everything manually if I first have to.

Plenty of users would disagree with you. It still saves you the trouble of having to look for and download the software and warns you of updates, for example.

In addition, the cask existing isn’t an issue for anyone. You’re free to not use it, it has no effect on how you use other casks.

> Since `brew cask install bluestacks` simply downloads the installer, `brew cask uninstall bluestacks` simply removes the installer but still leaves bluestacks installed on my computer.

That’s a wrong assumption. Just because it can’t install it, it doesn’t mean it can’t uninstall properly [and it already does plenty](https://github.com/Homebrew/homebrew-cask/blob/b593c4e3de4c565383487022110ac62c0f4ab556/Casks/bluestacks.rb#L16L26). It seems it indeed isn’t removing the app bundle right now, [which is a simple fix](https://github.com/Homebrew/homebrew-cask/pull/89715).

**Comment by TheKnarf** [comment]
Alright. Personally I would have preferred to get a result saying that the cask doesn't exist.
But nothing wrong with the project having a different opinion than me!

**Comment by vitorgalvao** [comment]
If you do `brew cask _stanza installer bluestacks`, the command will exit with `0`. If you try it on a cask without that stanza, it will return `1`.

You might want to use that to your advantage in our shell files, to ensure another cask like this is never considered in your particular setup.

**Comment by TheKnarf** [comment]
Thanks, that actually helps!

**Comment by core-code** [comment]
how about sending some feedback to the vendor about their awful installer? if every Mac user would send feedback to every vendor who tortures their users with PKGs  or (even worse) 'Installer apps' then we wouldn't have to endure this.
