### ISSUE TITLE
Question: Why is powershell a cask and not a formula 

### ISSUE THREAD

**Issue by aescolastico** [Homebrew/homebrew-cask#90088]
Hello,
Not really an issue. I was just curious about the motivation to put this in cask instead of formula. I thought formula was more for CLI tools and programming languages like powershell. Maybe I misunderstood the distinction.

**Comment by miccal** [comment]
Because it is easier to use the pre-complied `.pkg` provided by the PowerShell developers, and it includes the `.app` bundle `PowerShell.app`.

See [here](https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae) and [here](https://docs.brew.sh/Acceptable-Formulae#stuff-that-builds-an-app) for more information.

I hope that answers your question.

**Comment by aescolastico** [comment]
> Because it is easier to use the pre-complied `.pkg` provided by the PowerShell developers, and it includes the `.app` bundle `PowerShell.app`.
> 
> See [here](https://docs.brew.sh/Acceptable-Formulae#we-dont-like-binary-formulae) and [here](https://docs.brew.sh/Acceptable-Formulae#stuff-that-builds-an-app) for more information.
> 
> I hope that answers your question.

It does, thank you!
