### ISSUE TITLE
Add "brew cask pin" and "brew cask unpin" commands

### ISSUE THREAD

**Issue by ericbn** [Homebrew/homebrew-cask#90242]
### Description of feature/enhancement

Add "brew cask pin" and "brew cask unpin" commands that work like "brew pin" and " brew unpin" but for casks.

### Justification

Now that "brew update" without arguments updates all formulae and all casks, it's nice to have a way of pinning casks that we don't want to have updated. Plus, this brings "brew cask" closer to "brew", which is the direction the projects are heading.

### Example use case

E.g, I have robo-3t installed and I'm keeping version 1.2.1 (but 1.4.1 is the latest) because I need to use it with MongoDB versions 2 and 3, and newer versions of robo-3t do not support those. Since there's no way to do "brew cask pin robo-3t", I always need to be sure to call "brew upgrade --ignore-pinned --formula" instead of just "brew upgrade --ignore-pinned" as I was doing before.

**Comment by miccal** [comment]
Please see https://github.com/Homebrew/homebrew-cask/issues/49127#issuecomment-401501245

This has been discussed numerous times in the past, and is simply not something that can be meaningfully and consistently applied to Casks.

**Comment by ericbn** [comment]
I see. It still could makes sense to at least pin the casks that are not "auto-updateable", to flag the ones that we never want to upgrade manually (as it's the intention when we pin formulae, flagging those we never want to upgrade manually in the future). 

@vitorgalvao, do you want to reconsider this since now calling "brew upgrade" will also upgrade all casks that are not auto-updateable?

**Comment by vitorgalvao** [comment]
> @vitorgalvao, do you want to reconsider this

The only thing that changed since last time is that you no longer need to type `cask` to upgrade casks.

Seeing as that had no bearing at all on the decision, there’s nothing to reconsider, the same issues remain.

**Comment by ericbn** [comment]
A a note, I just learned that https://github.com/buo/homebrew-cask-upgrade implemented this feature.

**Comment by vitorgalvao** [comment]
> A a note, I just learned that https://github.com/buo/homebrew-cask-upgrade implemented this feature.

And they also have an order of magnitude fewer stars, which probably translates into even fewer users. Unless they’re deliberately breaking apps’ update mechanisms, they’ll face the exact same issues, except:

* Fewer users means means fewer bug reports.
* Being a third-party tool can mean less scrutiny and less complaints.

The last point is reinforced because a user who wants this feature and actively looks for a solution will find it on the third-party and read how it works. Us, on the other end, get regular issues for things that are clearly spelled out in multiple places of the documentation.

So again, nothing has changed based on that information, the underlying problem still exists for us.
