### ISSUE TITLE
google-cloud-sdk doesn't link binaries any longer

### ISSUE THREAD

**Issue by max-sixty** [Homebrew/homebrew-cask#94329]
#### General troubleshooting steps

- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/Homebrew/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).
- [x] I have retried my command with `--force`.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I have checked the instructions for [reporting bugs](https://github.com/Homebrew/homebrew-cask#reporting-bugs).
- [x] I made doubly sure this is not a [checksum does not match](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/checksum_does_not_match_error.md) error.

#### Description of issue

The google-cloud-sdk formula no longer copies or links the `gcloud` or `gsutil` binaries into a path that's accessible without running additional commands which mutate a shell config. Prior to that change, `gcloud` & `gsutil` were both accessible from `/usr/local/bin/gcloud`

I think that's a result of this PR: https://github.com/Homebrew/homebrew-cask/pull/91856/files#r520072203.

@jmo-qap pointed this out at the time, so possibly it's intended? It breaks some automated installs. Is there an upside to disabling the linking? Also tagging @xaocon, who kindly updated the formula to work with python3.8 in that PR.

**Comment by jmo-qap** [comment]
The removal of the linking does better match how gcloud SDK should have been installed by cask in the first place since the SDK binaries may change + the SDK updates itself, and therefore should manage getting onto the PATH without brew. However, I (and I'm sure I'm not alone) had code written that assumed the links created by brew existed on `/usr/local/bin` after brew installing the SDK. While the new version is more "correct", it is a backward incompatible change. Since it is very hard to pin versions in brew, I considered the behavior change a bug.

**Comment by max-sixty** [comment]
OK, thanks @jmo-qap . 

While I don't have enough brew-specific context to have a view on whether this was correct or not — the previous behavior was really useful!

**Comment by miccal** [comment]
Unfortunately the `google-cloud-sdk` cask does not work with the `python@3.9` formula and requires `python@3.8`, which is [a problem](https://github.com/Homebrew/homebrew-cask/issues/91744#issuecomment-719518210), hence this change.

If `google-cloud-sdk` can work with the latest version of `python` provided by `brew` that _is_ symlinked into `/usr/local`, we can then consider going back to the original behaviour for the `google-cloud-sdk` cask.

**Comment by xaocon** [comment]
@max-sixty, yeah, I can see how it was useful but the issue is that google-cloud-sdk manages it's own executables. just because you have google-cloud-sdk installed doesn't mean that `gsutil` is available. Creating a static list of symlinks means possibly installing broken symlinks into your /usr/local/bin, on the flip side, other executables that the current install doesn't download by default, like `appctl` still won't be symlinked into /usr/local/bin so you'll still need to update your `PATH` to look in the right place.

Even when it can go back to using the default python I don't think it's a good idea to create symlinks as was being done before.

**Comment by max-sixty** [comment]
On the narrow point — it has supported python 3.9 since Nov 10, according to this issue: https://issuetracker.google.com/issues/170125513

**Comment by max-sixty** [comment]
Appreciate your response @xaocon, though I don't completely understand the reason behind not adding the symlinks.

Is it that brew can't guarantee that there won't be other symlinks required (e.g. `appctl` is a good example) required, so it's better not to create any? Would creating those that previous existed and _also_ printing the caveat be a reasonable balance?

Or is it a general policy about creating symlinks for apps that manage their own executables?

I think the alternative for those who manage this as an automated install — assuming we don't want to change users' shell scripts — is to create the symlinks themselves — let me know if you can think of an easier way.

**Comment by xaocon** [comment]
@max-sixty, I think then thing to remember is that it's a package manager that installs a couple of apps people use by default. It installs apps in its own space. The executables may or may not be there depending on if you have them installed. This means making symlinks there by default is just guessing at what apps people have installed. Anyone not using all the defaults will either have broken symlinks or missing symlinks. There are some other ways to handle this but this seems the least intrusive and most "correct".
