### ISSUE TITLE
Use commandlinetools-mac and remove the android-sdk cask

### ISSUE THREAD

**Issue by lanzorg** [Homebrew/homebrew-cask#97372]
#### General troubleshooting steps

It's a shame homebrew is still using the deprecated android-sdk.
Even scoop has a proper commandlinetools package.
https://github.com/ScoopInstaller/Main/blob/master/bucket/android-clt.json

#### Description of issue

Spreading deprecated technologies is bad.

**Comment by reitermarkus** [comment]
> It's a shame homebrew is still using the deprecated android-sdk.

> Spreading deprecated technologies is bad.

Instead of opening an issue implying we are doing this on purpose, consider submitting a pull request to update/fix the `android-sdk` cask.

**Comment by lanzorg** [comment]
Sorry if I was a little harsh. I'm just hallucinating to see that the android-sdk cask is still available.

**Comment by vitorgalvao** [comment]
> Spreading deprecated technologies is bad.

The cask *specifically* warns you it has been discontinued when you `install` or `info` it:

```
android-sdk has been officially discontinued upstream.
It may stop working correctly (or at all) in recent versions of macOS.
```

It’s not harming or deceiving anyone. It’s being explicit and still has tons of users.

```
android-sdk
30 days: 3,060 (#36)
90 days: 10,631 (#33)
365 days: 50,098 (#77)
Age: 1386 days (added 2017, March 23)
```

Adding the command-line tools [has been tried but stopped](https://github.com/Homebrew/homebrew-cask/pull/80305). Instead of being snarky and ignoring our issue template, you could have used your time to get your facts straight about the cask or looked around if any work had already been done in this regard. We don’t work for you; if you want improvements, help us and your fellow users with meaningful research or a PR.
