### ISSUE TITLE
Edit mode for brew bump-cask-pr

### ISSUE THREAD

**Issue by tiiiecherle** [Homebrew/homebrew-cask#97544]
I used cask-repair for a long time. As it is marked as deprecated I'm trying to get familiar with `brew bump-cask-pr`.

I couldn't solve the following problem. The cask zettlr changed it's download url from
`https://github.com/Zettlr/Zettlr/releases/download/v#{version}/Zettlr-#{version}.dmg`
to
`https://github.com/Zettlr/Zettlr/releases/download/v#{version}/Zettlr-#{version}-x64.dmg`

When trying to submit this:
```
CASKNAME=zettlr
NEW_CASK_VERSION=1.8.5
brew bump-cask-pr "$CASKNAME" --version="$NEW_CASK_VERSION" --no-browse --url="https://github.com/Zettlr/Zettlr/releases/download/v#{version}/Zettlr-#{version}-x64.dmg"
```
I get 

```
==> Downloading https://github.com/Zettlr/Zettlr/releases/download/v1.8.5/Zettlr
Already downloaded: /Users/tom/Library/Caches/Homebrew/downloads/cfaf84944542a53f41cabbcf215889c3edcecdddb1038e697a22313a179c1bd6--Zettlr-1.8.5-x64.dmg
Warning: Cannot verify integrity of 'cfaf84944542a53f41cabbcf215889c3edcecdddb1038e697a22313a179c1bd6--Zettlr-1.8.5-x64.dmg'.
No checksum was provided for this resource.
For your reference, the checksum is:
  sha256 "2e6c54ebea9cc33e1d60f78325cc9f089812bef02bb4d8575c7260754a46f3b9"
==> replace /version\s+["']1\.8\.4["']/m with "version \"1.8.5\""
==> replace /https:\/\/github\.com\/Zettlr\/Zettlr\/releases\/download\/v\#\{ver
==> replace /sha256\s+["']bade8469da142bfadd58b8a598eeff28f40161bf351a1c5eccc86a
audit for zettlr: failed
 - The URL's domain github.com does not match the homepage domain www.zettlr.com, a `verified` parameter has to be added to the `url` stanza. See https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-verified
Error: 1 problem in 1 cask detected
Error: `brew audit` failed!
```

This line is already included in the cask:
`,verified: "github.com/Zettlr/Zettlr/"`

How do I add this to `brew bump-cask-pr`?

If possible or not either way it would be nice if `brew bump-cask-pr` would have an --edit-cask mode like cask-repair.

Thanks a lot for looking into it.

**Comment by miccal** [comment]
Unfortunately there is no way to edit a Formula or Cask file using the `brew bump` commands -- if you need to make these sort of changes, you will have to do it via `git` as explained [here](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#submitting-your-changes).

**Comment by vitorgalvao** [comment]
> I used cask-repair for a long time. As it is marked as deprecated

To clarify, all that means is that I no longer intend to add features or spend time on debugging issues, especially those caused by `hub` (the number one cause of problems). `cask-repair` will continue to work for the foreseeable future—likely years and years—*and* I will still review and accept PRs to fix any problems.

So if you like features of `cask-repair`, keep using it. By design, `brew bump-cask-pr` won’t reach `cask-repair`’s level of flexibility, but it will perform the simpler tasks more reliably.

My suggestion would be to use `brew bump-cask-pr` by default and `cask-repair` when you need it. Or just use `cask-repair` like you always did, because if it ever breaks and you don’t wish to submit a PR to fix it, `brew bump-cask-pr` is simple enough to start using then.

Though now that I think about it, I could also revamp `cask-repair` to use `brew bump-cask-pr` internally and add the editing features on top. No promises that I will, though.

**Comment by tiiiecherle** [comment]
@vitorgalvao 
Thanks for the Feedback. I don't know if it is an option but if there should only be one tool in the future perhaps a few features of `cask-repair` could be integrated into `brew bump-cask-pr`.

Thanks for all all the great work the complete homebrew team is doing ;)
