### ISSUE TITLE
Can not install python3 using  brew install command

### ISSUE THREAD

**Issue by LiangYu45** [Homebrew/homebrew-cask#98731]
I just tried to install python3 in my mac , but it shows that :

% brew install python3
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "python3".
It was migrated from homebrew/cask to homebrew/core.

So what is the problem?

**Comment by adithyasunil26** [comment]
I am not able to replicate this error so it must be something wrong with your local repository. 
Are you facing this issue only with python3 or other packages as well?

If the issue is with all packages then you might want to check https://github.com/Homebrew/homebrew-core/issues/37724 .

If the issue is only with python3 you can try python@3.9 since python3 is an alias for python@3.9.
```bash
brew install python@3.9
```
^This does not fix the issue but it gets the job done for now if the problem is the alias being absent in your local repo for some reason.
You can try fixing this with a ```brew update-reset``` or uninstall and reinstall (https://github.com/homebrew/install).

**Comment by miccal** [comment]
`python` is a Formula, not a Cask -- you have reported this issue to the wrong repository. 

Please report this to https://github.com/Homebrew/homebrew-core and ensure that you fill out the issue template.
